### ISSUE TITLE
Compilar y disponer la información de la linea base, a partir de los datos disponibles del IAvH y EPM

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#101]

**Comment by cazapatamar** [comment]
Se creó un bucket llamado `epm-humboldt` y dentro de este una carpeta llamada `1-linea-base`. Falta crear el usuario para Julián y asignarle los permisos

Documentación encontrada para este proceso:
https://docs.aws.amazon.com/es_es/AmazonS3/latest/userguide/walkthrough1.html#walkthrough1-add-users

**Comment by cazapatamar** [comment]
Se subió el archivo entregable de la GDB (`GDB_Producto_1.1.EPM.gdb.zip`) en el bucket de S3 en la siguiente ruta:

epm-humboldt/1-linea-base/

El archivo tiene acceso público para descarga
