### ISSUE TITLE
Script para descarga de recursos asociados a metadatos

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#103]
Realizar script para descarga de metadatos para la siguiente [lista](https://docs.google.com/spreadsheets/d/12QV9vooP8j9lIoevHCHDjeF6v-HszuLh/edit#gid=1346125953) de metadatos (Hoja `Hoja Camilo Revisar por Fa`)

**Comment by cazapatamar** [comment]
En Excel se pudo obtener la ruta a los archivos de cada metadato

@danflop porfa revisar

**Comment by cazapatamar** [comment]
@alegnaaived va a realizar el script para copiar los recursos de acuerdo al Excel

**Comment by alegnaaived** [comment]
Copia finalizada en /mnt/datosgn_test/datos_bryan/20210929. El script está en la carpeta /mnt/datosgn_test/datos_bryan.

![image](https://user-images.githubusercontent.com/15584917/135341993-e6f45393-e2f6-4db1-8ac9-04dc32a8092c.png)

**Comment by cazapatamar** [comment]
En el listado de excel hay 118 metadatos y veo que en la carpeta `datos_bryan` hay 115 subcarpetas.

Verifiqué a los 2 que le pusiste el comentario de `No existe esa ruta del recurso` y efectivamente parece como si se hubieran borrado de la plataforma por que no aparecen en la base de datos.

@alegnaaived de pronto cuando ejecutaste el script identificaste algún otro que no se copiara o que no existiera la carpeta para ese id como en los 2 casos anteriores?. Es que creo que faltaría uno: 115 + 2 = 117.

**Comment by cazapatamar** [comment]
@danflop ya esta tarea quedó culminada y ya se pueden adelantar las gestiones para dar los permisos a Bryan sobre la carpeta
