### ISSUE TITLE
Crear repositorio para almacenar scripts de cálculo de indicadores

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#105]
Crear el repositorio que van a usar Maria Isabel y Maria Alejandra para versionar los códigos de cálculo de indicadores (el segundo lambda de la arquitectura)

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/105?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84
