### ISSUE TITLE
Deshabilitar generación automática de citaciones 

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#114]
### Descripción del problema
Se presenta un bug en la versión 2.5.0 del ipt/Gbif que genera el error, mostrado a continuación, cuando el usuario ingresa a al formulario de edición de metadatos en la sección de **REFERENCIAS**. 
El error ya esta reportado este [issue](https://github.com/gbif/ipt/issues/1655) del repositorio de Gbif.

![Screenshot_20211014_160658.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/3c49e277-1a58-41a0-8b6f-977a7b33810c)

El error no esta relacionado con el warning que se presentaba al realizar la migración de los recursos a la nueva versión.

La nueva versión de ipt tiene una funcionalidad de generación automática de links para citaciones y esta configuración esta relacionada con los DOIs que se asignan de forma automática para su publicación en Gbif. Como no necesitamos  campos asociados con DOI el equipo temático sugiere que no vale la pena dejarlos en funcionamiento.

La idea es buscar una forma de eliminar la generación automática de citaciones, para que el campo señalado con azul **Como referenciar este recurso?** se siga diligenciando manual, y saltar todas  validación y generación de DOIs para que el campo señalado con rojo **Identificador de la Referencia Recurso** también sea manual y se tomen los valores que tienen los recursos en esos campos en este momento.

![Screenshot_20211014_111954.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/7d763d8d-4368-4dc1-b8fc-6ad4df0b2a4c)

NOTA:
Si en la versión 2.5.0 existen campos adicionales relacionados con el DOI se deben ocultar de la interfaz.

**Comment by alegnaaived** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/114?planning-poker) with ZenHub @Trjegul84 @danflop @cazapatamar @erikasv

**Comment by erikasv** [comment]
Esta tarea se deja abierta hasta que arreglen el issue desde el IPT, en ese momento se revisa y se decide si toca hacer algún ajuste relacionado con esto.

**Comment by alegnaaived** [comment]
El release que estamos esperando es 2.5.2

**Comment by erikasv** [comment]
Ya no toca hacer nada para esta tarea pues se arregló con la actualización del IPT
