### ISSUE TITLE
Identificar una estrategia o herramienta para automatizar la carga de datos geográficos

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#116]
### Descripción
Se probó Koop y se identificó que no hace el paso de cargar de forma automática a través de un servicio la carga de capas. Esta es una funcionalidad que tiene Geoserver y es la que se busca implementar de forma más liviana con otra solución y que corresponda a una herramienta integrada en la futura solución.

### Resultado esperado
 - Revisar otra herramienta que permita publicar un servicio web para cargar un .zip con shapefile en PostGis.
 - En caso de no encontrar una única herramienta, plantear una estrategia que utilice una o más herramientas.

**Comment by erikasv** [comment]
Se opta por intentar otra estrategia:

- Tener un servidor en express que use koop como un middleware para servir las capas para un visor
- Implementar un endpoint que reciba el zip y cargue la capa a postgis haciendo uso de shp2pgsql

Esta implementación quedó en proceso

**Comment by erikasv** [comment]
Al final se logró implementar la última estrategia con éxito, quedamos a la espera de nuevos requerimientos para determinar si son compatibles con esta implementación.

El repositorio asociado es: https://github.com/PEM-Humboldt/herramienta-resiliencia-servidor
