### ISSUE TITLE
Actualizar información sobre los servidores del PEM

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#12]
Tenemos dos documentos con la información de los servidores y las aplicaciones que administramos. Actualizar la información de ambos.

Los documentos son "Servidores PEM" e "Inventario de servidores y aplicaciones".

# Consideraciones
- A pesar de que está duplicada la información, en el documento de texto deben quedar todas las aplicaciones activas, en la hoja de cálculo deben quedar todas, aunque no estén activas o desconozcamos el responsable
- En el documento de texto hay una sección de la nube, listar ahí sólo aquellas que correspondan a I2D, BioTablero o BioModelos, no se debe incluir todo lo relacionado con proyectos
- En el documento de texto incluir un enlace a los repositorios de gitlab que tienen información de las máquinas en el datacenter y en cada nube

**Comment by cazapatamar** [comment]
Avance 25/01/23:

- 192.168.11.42
- 192.168.11.63
- 192.168.11.78
- 192.168.11.35
- 192.168.11.59
- 192.168.11.105

**Comment by cazapatamar** [comment]
Se finaliza la actualización de la documentación. Queda pendiente verificar con TI si los servidores .60 y .70 contienen algo que se esté usando actualmente pero aparentemente de nuestro lado no hay nada util. Solo se identifican versiones antiguas de aplicaciones que ya fueron migradas a otros servidores.
