### ISSUE TITLE
Liberar espacio de disco en el servidor de BD relacionales

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#124]
Revisar los archivos de backup que se encuentran de manera local en este servidor identificando su fuente y revisando la posibilidad de moverlos con ayuda de TI a el servidor de almacenamiento Institucional.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/124?planning-poker) with ZenHub @danflop

**Comment by Trjegul84** [comment]
Se coordinó con TI la restauración de las unidades del servidor remoto. Se montaron de nuevo, ahora ya se puede pasar información de backups a ese servidor.
