### ISSUE TITLE
Generar Docker compose para desplegar un Geoserver

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#125]
### Consideraciones
Tener en que se debe levantar la base de datos en un contenedor aparte.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/125?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by erikasv** [comment]
Se creó docker-compose en una [rama](https://github.com/PEM-Humboldt/herramienta-resiliencia-servidor/compare/useGeoserver) aparte en la que se desea continuar el trabajo con la tarea #126

Se dejó el contenedor para postgis porque será el que utilice el servidor, sin embargo para lo que vamos a usar el geoserver no requiere postgis.
