### ISSUE TITLE
Transferir repositorio

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#128]
- [x] Actualizar el README del repositorio para indicar la licencia MIT, preferiblemente agregar el archivo de la licencia.
- [x] Transferir el repositorio que se tiene actualmente para la página de WePlan a la organización del PEM.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/128?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84

**Comment by alegnaaived** [comment]
[Enlace al repositorio](https://github.com/PEM-Humboldt/weplan-colombia-website)
