### ISSUE TITLE
Mencionar (o enlazar) el trabajo de IIS en la página de WePlan

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#129]
Coordinar con César y/o Marcelo cómo enlazar (o reconocer) el trabajo previo de IIS en el nuevo sitio.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/129?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84

**Comment by alegnaaived** [comment]
Se incluyó el logo de IIS en el footer de WePlan en la tarea [dev-scrum/127](https://github.com/PEM-Humboldt/dev-scrum/issues/127) y en el código fuente se menciona que el trabajo fue desarrollado a partir del sitio de WePlan

**Comment by alegnaaived** [comment]
Además, Marcelo mencionó que él incluirá en el texto que está pendiente la mención dentro del sitio web que estamos desarrollando, que este sitio es basado en el trabajo de IIS para el sitio oficial de WePlan
