### ISSUE TITLE
Revisar íconos de ayuda

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#131]
El primer punto de la sección `Dentro de la edición de metadato` de la revisión que hizo Carolina menciona que los contenidos de los iconos son incorrectos.

Esto es algo que se tuvo en cuenta cuando se realizaron las adecuaciones para Ceiba, por lo tanto es necesario revisar si los cambios se perdieron al actualizar con la última versión del IPT o si están correctos y se debe discutir con Carolina.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/131?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84

**Comment by alegnaaived** [comment]
Se realizó una reunión y se identificó que hace falta crear iconos de ayuda en CEIBA 2.5.1. Además, durante la reunión se revisó que ya está disponible el código del IPT en su versión 2.5.2, lo cual corrige el error que ocurre al acceder a la sección de referencias en el recurso.
