### ISSUE TITLE
Borrar datasets de prueba

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#140]
Se debe eliminar los 5 datasets que se crearon para pruebas tanto de base de datos como los archivos relacionados.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/140?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84

**Comment by Trjegul84** [comment]
Se borró el dataverse de prueba prueba creado durante las "pruebas".
Se borraron los datasets creados durantes las pruebas para que la ptalaforma quede con los datasets originales que publicó D.R.
Para borrar los datsets se realizaron los pasos descritos en el [Manual de Administrador de Dataverse](https://dataverse.scholarsportal.info/guides/en/latest/api/native-api.html#delete-published-dataset)
También se borraron los datasets bloqueados debido a la configuración inicial por defecto con DOIs establecidos por la plataforma y no los DOIs falsos.
Cuando se borraron los datasets de pruebas se procedió a verificar que se borre el rastro en la base de datos, se eliminaron de la tabla  que se eliminó el rastro de la tabla `dvobject` en la base de datos. Sin embargo, se observa que áun existen archivos con los nombres de los identificadores de los datasets borrados en las carpetas de glassfish. Esto no afecta la plataforma ni se observan los elementos borrados, pero no se encontró cómo hacer para eliminar mediante comandos estas referencias en las carpetas de glassfish, hasta el momento si se quiere eliminar este rastro en glassfish se debe hacer de forma manual.
