### ISSUE TITLE
Geoserver y Postgres en AWS

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#142]
**Descripción:**

No está respondiendo a peticiones externas. Ya se realizó una revisión con @Trjegul84 y @danflop .

**Objetivo:**

- [ ] Desplegar en AWS los contenedores Geoserver Institucional y Postgres, y revisar con Julián.

**Comment by cazapatamar** [comment]
Se crearon 2 máquinas EC2 en AWS así:

- 54.166.78.137: Base de datos postgis donde se restauro el backup de la base de datos anterior. Los otros datos de acceso son las mismas que la anterior y que están documentadas.
- [http://44.195.233.148:8080/geoserver/](http://44.195.233.148:8080/geoserver/): Nueva instancia de geoserver versión 2.18 donde se restauró el directorio `data` de la instancia anterior. Se pueden ver los workspaces y data stores pero al consultar las capas se queda cargando y no responde. Esto se puede dar por que el origen de los datos está apuntando a la base de datos anterior para lo cual Julián está revisando si estos datos se pueden cambiar a traves de geoserver. Se está a la espera de la respuesta por parte de Julián.

Pendiente: Si la restauración de geoserver es exitosa solo queda faltando conectarla al backend y de esta forma dejar de usar la instancia anterior. Si no es exitosa entonces se recomienda ver que alternativas hay para realizarla. Como última opción es montar una instancia limpia de geoserver y volver a subir manualmente todos los datos.
