### ISSUE TITLE
Crear ambiente de prueba para actualización de GeoServer

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#153]
Crear una máquina en aws con la versión estable más reciente de GeoServer (en docker) para probrar la actualización del servicio institucional.

Una vez creada la máquina y puesto en marcha el GeoServer, realizar la migración de los datos (con una copia) para que Julián pueda revisar si la migración se realiza correctamente.

## Consideraciones
- De acuerdo a la explicación de Julián la migración debería realizarse simplemente sobrescribiendo la carpeta de datos con los datos de la versión anterior, sin embargo puede que hayan algunas complicaciones, se recomienda buscar si existe una guía de migración o algún tutorial de la comunidad.
- Tener en cuenta la base de datos asociada al GeoServer y que también hay que levantar un servidor de postgres, se recomienda levantarla en la misma máquina.
- Sacar tanto los datos como la base datos de lo que hay en el datacenter.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/153?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Se monta una maquina en AWS llamada `spike-upgrade-geoserver` de tipo `t3.medium` con los siguientes contenedores:

- Postgres con los datos restaurados del datacenter (Bases de datos `servicios_web` y `i2d`)
- Geoserver versión 2.20.2 desplegado en [http://34.238.22.20:8080/geoserver](http://34.238.22.20:8080/geoserver) con los datos restaurados del datacenter

Los datos de acceso al geoserver son los mismos que los de la instancia del datacenter
