### ISSUE TITLE
Actualizar versión de Docker en servidor 78

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#154]
Se debe actualizar la versión de Docker actual (17.05.0) del servidor 78 a la versión 20.x.x 

Tareas:

- [ ] Realizar un backup de GitLab
- [ ] Verificar si el contenedor de Biomodelos y el contendido de carpeta visor-back no involucrarán afectaciones
- [ ] Actualizar versión de Docker
- [ ] Verificar el correcto funcionamiento de GitLab

**Comment by erikasv** [comment]
Duplicado de #155
