### ISSUE TITLE
Investigar cómo crear el demonio para script de crossRef

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#159]
Investigar cómo construir el demonio para ejecutar el script de enlace con crossRef en el servidor de Dataverse AWS.
Tener en cuenta:
- Revisar el código del script
- Revisar instrucciones (si se adaptan a nuestra instalación)

## Resultado
Instrucciones para crear el demonio (ideal si se genera el código de una vez)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/159?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se cargó al servidor el código del script de crossref, se modifico según instrucciones y, se configuro, activó y se puso en ejecución. Fue necesario instalar las librerías de python` crossrefapi y` `jinja2`. 
Aunque el servicio se encuentra activo y corriendo no se ve ningún efecto en nuestra instancia de Dataverse. Se realizó una prueba creando un nuevo dataset pero el script no asigna el DOI e incluso se esperaba que actualice los dois de los datasets actuales pero no ejecuta ninguna de estas acciones.

Es necesario analizar las posibles causas de la falla y posteriormente redactar el caso para enviar al foro de la comunidad especialmente al creador del script.
