### ISSUE TITLE
Despliegue sitio de WePlan

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#162]
Desplegar desarrollo de sitio de WePlan como sitio estático en el servicio S3 de AWS. 

Como resultado de esta tarea se espera que el sitio de WePlan quede público y accesible a una URL de AWS.

**Comment by alegnaaived** [comment]
El enlace al sitio es http://weplan-colombia.s3-website-us-east-1.amazonaws.com/
