### ISSUE TITLE
Revisar modificación a basisOfRecords

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#167]
### Descripción
Carolina nos plantea la siguiente inquietud en el correo de la revisión de Ceiba Staging: 

_Tengo una pregunta adicional, este nuevo IPT nos obliga a realizar una traducción de la columna “basisOfRecord” en la sección del mapeo que está asociado al vocabulario controlado que manejan para esa columna que es ingles, si no se agrega esa traducción no deja publicar, por lo tanto los recursos nuevos quedarán con esta columna en ingles y los antiguos que no se republiquen quedarán en español. Mi pregunta es si es posible eliminar el tema de la traducción, no sé si es posible eliminar ese vocabulario controlado que exigen la herramienta para ese campo._

Se desea identificar si se puede eliminar el vocabulario que forza la traducción o identificar la forma de unificar a idioma español este campo. Pero en caso de ser un cambio complejo se debe discutir con Carolina que tan necesario es este cambio.

### Resultado esperado
Revisión de la situación y si hay una posible solución o qué tan complejo sería un cambio a nivel de código.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/167?planning-poker) with ZenHub @alegnaaived @Trjegul84

**Comment by alegnaaived** [comment]
Comencé a revisar las [notas de los release](https://www.gbif.org/es/release-notes) para identificar en qué versión están los cambios de basis of record. Identifiqué las versiones de _28 February 2022_ y _31 January 2022_ con cambios en esa sección, así que revisaré en detalle los cambios de esas fechas.

Encontré que el control del campo hace parte del [programa de trabajo de GBIF durante 2020](https://docs.gbif.org/2020-work-programme/en/#_2020_work_items_8) y creo que esas directrices cambiaron el vocabulario de basisOfRecord.

Seguiré revisando y le consultaré esto a Carolina.

**Comment by alegnaaived** [comment]
Validamos con Carolina que el problema no es que el IPT cambie un valor en basisOfRecord, sino que el problema es que basisOfRecord sea un campo obligatorio para la traducción.
