### ISSUE TITLE
Ajustar scripts de limpieza de Geonetwork

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#169]
## Descripción
Existe un script encargado de limpiar los archivos temporales dentro del contenedor donde se encuentra GeoNetwork. Sin embargo la tarea crontab para su ejecución está mal configurada en cuanto a la ruta del script.

También se ha detectado un tráfico inusual con un endpoint del API para la exportación de los archivos .mef que genera archivos temporales. Revisar con el equipo de GeoNetwork.
 

## Resultado
Ajustar el script de limpieza y ejecutar el crontab para que lo ejecute.

## Consideraciones
- Se recomienda que esta tarea sea un seguimiento durante toda la semana.
- También se recomienda ejecutar manualmente el script y verificar si sí está borrando los archivos correspondientes

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/169?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/169?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84

**Comment by cazapatamar** [comment]
Se encuentra que el script se encuentra es en la maquina host y no en el contenedor. Se copia al contenedor usando `docker cp`. Se ejecuta manualmente desde el host usando `docker exec geonetwork_v322_iavh /bin/sh -c "clean_tomcat_temp.sh"` y parece funcionar:

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/ca23d086-6e06-4258-a815-737d6713ffe1)

Se encuentra que algunos archivos no los borra, se hace necesario hacer seguimiento pero puede ser por que esos archivos esten siendo usados por la aplicacion en ese momento.

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/0bf17d3b-4642-4152-9560-d1ffdcac05cb)

Se seguirá haciendo seguimiento sobre el script en los próximos días de tal manera que se pueda evaluar efectividad del cron y del script como tal.

**Comment by cazapatamar** [comment]
Se ha hecho seguimiento durante los ultimos 3 dias y se concluye que el script se está ejecutando sin problema.
