### ISSUE TITLE
Revisar modelos de datos AMVA y generar script de la o las vistas necesarias

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#171]
# Descripción
Se generó un modelo de datos ER para el proyecto AMVA, el cual se va a entregar para que ellos creen la bd en sus servidores (Personas en medellín que no recuerdo la entidad?). Va a ser en Oracle. Este es el [modelo](https://app.diagrams.net/#G19DSAXD4q2RJzhZ1OEYnuMrYksMjsp8aZ).

Se debe revisar el modelo ER, cambiar los tipos de datos usados en bases de datos Oracle. Finalmente reunirse con Marcelo para aclarar que se espera de las vistas e idealmente generar el script para crearlas en Oracle.

# Resultados

- Modelo ER ajustado y con tipos de datos de Oracle
- Scripts de creación de vistas

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/171?planning-poker) with ZenHub @alegnaaived @danflop @erikasv @Trjegul84

**Comment by erikasv** [comment]
@cazapatamar por favor agregar a la tarea el resultado esperado, entiendo que son los scipts, pero el último parráfo da indicios de que también se espera el modelo refinado

También mover el documento donde está el modelo a una carpeta dentro de [2022](https://drive.google.com/drive/folders/1abVAq-JJWj5ErFfWe2RyJEtAPVHzS9dM) y ajustar los permisos par aque podamos verlo

**Comment by cazapatamar** [comment]
Ya se revisó el modelo ER con Marcelo, multiplicidad y tipos de datos de los campos.

Se acordó que se van a generar 12 queries, una para cada especie, los cuales van a servir para generar las 12 vistas necesarias para el aplicativo. Se espera entregar a final de la semana (1 de Abril)

**Comment by cazapatamar** [comment]
Se generó el [script](https://drive.google.com/file/d/1EJhMcT8frd04y5D14Tj3slzWw28mZyeR/view?usp=sharing) de creación de las 14 vistas y se envían al equipo que está montando la base de datos.
