### ISSUE TITLE
Crear archivo excel para las traducciones

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#174]
# Descripción
Se necesita un archivo excel del archivo Bundle.properties para iniciar la tarea de las traducciones de Dataverse este debe tener las siguientes columnas: 
- Nombre de propiedad
- Traducción actual en inglés
- Traducción disponible en español (esto es lo que esta desactualizado)
- Campo para nueva traducción

Para crear este archivo es necesario realizar una comparación entre las propiedades que tiene el archivo Bundle.properties en Inglés en la versión mas reciente y las propiedades que existan en el archivo en Español puesto que algunas propiedades tienen nombres obsoletos o no existen en el archivo es_ES será necesario procesar estas columnas y obtener aquellas traducciones que puedan ser reutilizadas. 

# Resultado
- Archivo con cuatro columnas y convención de colores para identificar estado de traducciones. 
- Proponer una estrategia de trabajo en equipo para repartir la tarea de traducir basada en ese archivo. Se debe crear una nueva tarea en la que se hagan las asignaciones, similar a como se realizó la documentación de AWS

# Consideraciones
Al realizar la comparación entre el archivo de propiedades en inglés y el de la versión vieja en español limitarse a buscar aquellas que no han cambiado de nombre o que sea muy claro que su nombre cambió sólo un poco, no es necesario buscar exhaustivamente cual debería ser la propiedad equivalente.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/174?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se creo el [archivo de traducciones de dataverse](https://docs.google.com/spreadsheets/d/1fhakZE_y4TLaFbNsExbFlKi6qH8h5n5M/edit?usp=sharing&ouid=112118080811729441231&rtpof=true&sd=true)
La columna `A` es un id que se genera al generar el archivo. (Se recomienda dejar ese id para identificar la linea)
La columna `key` es la variable (actualizada) de acuerdo al archivo más reciente disponible en el repositorio de lenguajes de Dataverse.
La columna `englishdata` es la traducción de la variable en Inglés
La columna `spanish_data` es la traducción disponible tomada del repositorio desactualizado. Los espacios en blanco de esta columna son los que se deben traducir aunque también se debería revisar las traducciones existentes porque no hay seguridad de su correcta traducción.
En la pestaña convenciones se encuentran los colores para indicar por cada linea el estado/avance de una traducción.
