### ISSUE TITLE
Investigar cómo reemplazar link de Soporte por link hacia Wiki

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#175]
Se requiere revisar si es posible reemplazar el link de `Soporte` en la página inicial de Dataverse por un link hacia la Wiki, Se debe identificar si ese cambio se puede realizar modificando él código o mediante opciones del API para customización de la interfaz o por la interfaz del administrador. 

Si la opción de reemplazar el link es muy compleja e involucra borrar mucho código la otra opción es revisar si en lugar de cambiar el link se puede ocultar.

Se debe realizar pruebas del funcionamiento, por ahora con un link de prueba mientras se configura la wiki de Dataverse.

# Resultado
Documentación del proceso para cambiar el link de soporte por otro link en nuestra plataforma Dataverse

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/175?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84
