### ISSUE TITLE
Ajustar traducciones de dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#181]
# Descripción

Corregir o mejorar las traducciones del [archivo](https://docs.google.com/spreadsheets/d/1fhakZE_y4TLaFbNsExbFlKi6qH8h5n5M/edit#gid=112629628) de traducciones para Dataverse, una vez se finalice, Diego deberá revisar las traducciones.

- [x] @cazapatamar De la linea 2 a la 685
- [x] @danflop De la 686 a la 1370
- [x] @erikasv De la 1371 a la 2055
- [x] @Trjegul84 De la 2055 a la última

# Resultado
Archivo listo para ser cargado en la aplicación

# Consideraciones
Después de que se propongan las traducciones recordar cambiar los caracteres especiales del español, como tildes y ñ

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/181?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Se realizaron las traducciones de la linea 2 a la 685
