### ISSUE TITLE
Diagnosticar máquina de dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#183]
# Descripción

Se han identificado algunos incrementos espontáneos en la máquina de dataverse, se debe identificar por qué sucede esto y definir si hay algo que se pueda hacer para disminuir costos

# Resultado

Diagnostico del problema y posible solución.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/183?planning-poker) with ZenHub @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se detuvo el demonio de registro de DOIs (`doi.py`) con CrossRef para descartar o confirmar que esta esa la causa de los altos costos Se debe tener en cuenta  desde el día de hoy 26/04/2022 esta detenido. 
El demonio se activó por primera vez el día 03 de Marzo de 2022.

**Comment by Trjegul84** [comment]
Se revisaron las máquinas de AWS y se observa con más detalle y se determina que la que está consumiendo procesador es la máquina del Geoserver y no la de dataverse.

**Comment by danflop** [comment]
Se debe generar nueva tarea para revisar el despliegue de la máquina en la nube de geoserver.
