### ISSUE TITLE
Diagnosticar máquina de Geoserver en AWS para controlar uso de créditos de CPU

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#187]
Actualmente la máquina que se utiliza para la aplicación en Geoserver en EC2 es una t3.medium (visor-geoserver) que está reportando un uso alto de créditos de CPU. Es importante definir qué otro tipo de máquina se puede desplegar esta  herramienta para optimizar los requerimientos de la herramienta y disminuir este consumo adicional.

Para conocer más sobre el cálculo de los créditos de uso de la CPU se puede revisar el siguiente [enlace](https://docs.aws.amazon.com/es_es/AWSEC2/latest/UserGuide/burstable-performance-instances-monitoring-cpu-credits.html)

# Resultado
Definición de la máquina que deberíamos usar para GeoServer

# Consideraciones
Revisar la viabilidad del monitoreo individual de la máquina (en términos de costo)

**Comment by Trjegul84** [comment]
Al revisar la documentación de las instancias EC2 es importante tener en cuenta que:

Las instancias T ofrecen un equilibrio de recursos de cómputo, memoria y red, sirven para aplicaciones de uso general que tienen un uso de la CPU de bajo a moderado. Las instancias EC2 ampliables consisten en los tipos de instancias T4g, T3a y T3. Las instancias T4g son las instancias ampliables de última generación, este tipo de instancia es de menor costo con una relación precio-rendimiento hasta un 40 % superior y un costo 20 % menor en comparación con la T3.

Las instancias T4g ofrecen hasta un 40% más de desempeño por el precio que las instancias T3 y son apropiadas para un amplio conjunto de cargas de trabajo de propósito general en ráfagas, incluidos los microservicios, las aplicaciones interactivas de baja latencia, las bases de datos pequeñas y medianas, los escritorios virtuales, los entornos de desarrollo, los repositorios de código y las aplicaciones críticas para el negocio además ganan créditos de CPU cuando las cargas de trabajo funcionan por debajo del umbral de referencia. Cada crédito de CPU acumulado puede utilizarse para alcanzar el máximo rendimiento del núcleo de la CPU durante un minuto. 

Se concluye que una opción para la máquina del Geoserver en AWS sería usar la máquina T4g para ahorrar cuando el uso de créditos de CPU es alto.
