### ISSUE TITLE
Revisar servicio docker de Biotablero

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#192]
Problema:
No se esta reiniciando el servicio de docker cuando hay cortes de energía (otras máquinas si se recuperan después de una falla menos Biotablero). Revisar logs de la máquina y hacer backup de los archivos de configuración del servicio. 
[Ver Documento](https://docs.google.com/document/d/1bNc2_e3javjbBXZIkXvjSkE0C53dR5AZuKOfTQb9dXY/edit?usp=sharing)

Resultado:
Contenedores docker de Biotablero arrancan automáticamente después de un evento de reinicio.

**Comment by erikasv** [comment]
Esto se resolvió con la última caída, se habilitó el servicio, también se resolvió para el 78
