### ISSUE TITLE
Cambiar comportamiento de selector de licencia en Ceiba v.2

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#201]
Grupo temático reportó un comportamiento no deseado en el selector de licencia al editar los metadatos del recurso.
Se debe revisar que sucede con la opción Libre a nivel interno con notificación previa, por qué no queda con la leyenda correcta el selector una vez se ha editado los datos.
Resultado:
Selector de licencia de la sección edición de metadatos queda con la misma opción por defecto previamente seleccionada.

**Comment by Trjegul84** [comment]
No se logra arreglar el comportamiento del selector de licencia cuando se edita los metadatos básicos de un recurso.
Se encuentran dos posibles opciones para dar solución:
- Cambiar la lógica que maneja el selector de licencias en las líneas de javascript  del archivo `...pages/manage/eml/basic.ftl`
- Cambiar la forma en que se realiza la consulta de las llaves del arreglo de licencias, o ensayar otras funciones de StringUtils en el código de la función `getLicenseKeySelected` del archivo MetadataAction.java 

NOTA:
Revisar las instrucciones al final de este [documento](https://docs.google.com/document/d/10e6FK75w1heSIugNst15i0GpDmqTjCcB6amNcYcL2sQ/edit?usp=sharing) para tener un ambiente local donde realizar puebas y modificaciones de la nueva versión de Ceiba.

**Comment by erikasv** [comment]
Se planea hacer reuniones con cada miembro del equipo para intentar resolver el problema sin necesidad de que todos levantemos el ambiente en local

**Comment by erikasv** [comment]
Se acota el alcance a la exploración en dichas reuniones

**Comment by Trjegul84** [comment]
Se realiza cambio del nombre de la variable license.name.npiavh  de `Libre a nivel interno con notificaci\u00f3n previa` por `Libre en nivel interno con notificaci\u00f3n previa` en todas los archivos `.properties `y en la lógica de la interfaz `overview` y en `edit metadata`
