### ISSUE TITLE
Actualizar ambiente de pruebas de Ceiba

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#206]
Actualizar el ambiente de pruebas para que quede al día

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/206?planning-poker) with ZenHub @Trjegul84

**Comment by Trjegul84** [comment]
Se actualizó el ambiente de pruebas de Ceiba 2 con el último .war generado con las modificaciones al selector de licencia en la sección de modificar metadatos.
