### ISSUE TITLE
Intentar ejecutar script desde un endpoint

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#211]
# Descripción

A partir de los resultados de la tarea [210](https://github.com/PEM-Humboldt/dev-scrum/issues/210) se desea poder ejecutar un script desde un llamado directo al servidor sin usar la interfaz web que dispone la aplicación.

Es probable que no se pueda ejecutar un script directamente sino que deba hacerse a través de un pipeline, en ese caso sería necesario configurar un pipeline que ejecute sólo un script con las entradas definidas.

Deseable poder pasar las entradas al momento de ejecución del pipeline o script en lugar de tener que definirlas en el .json

# Resultado
Ejecución de un script o pipeline sin hacer uso de la interfaz web

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/211?planning-poker) with ZenHub @ManuelStardust @cazapatamar

**Comment by ManuelStardust** [comment]
Se logro la ejecución de scripts y piplines de manera independiente. Se probaron los end points disponibles según el Readme del componente del servidor https://github.com/GEO-BON/biab-2.0/blob/main/script-server/README.md. Finalmente se elaboró un archivo de Insomnia para estos endpoints y se hizó un commit con este archivo.
