### ISSUE TITLE
Hacer pruebas de desempeño

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#212]
# Descripción
Una de las actividades de ecopetrol son las pruebas de desempeño de la herramienta, y para la entrega habrá que hacer un informe de las mismas.

Se desea poner en el informe algunos datos como:
- Cuántas peticiones se pueden hacer a la vez
- Restricciones (como la de un usuario por workspace)
- No sé que tan buena idea sea poner el tiempo que toma la ejecución del modelo, supongo que un aproximado sería lo que esperan
- Otros datos que puedan salir

# Actualización 01-08
Actualizar ambiente de aws

# Resultado
Informe de pruebas de desempeño

# Consideraciones
No es necesario hacer nada exhaustivo, pero se pueden mirar si hay alguna herramienta como jmeter que valga la pena usar

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/212?planning-poker) with ZenHub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se exploraron varias hehrramientas para pruebas de rendimiento para APIs, logrando buenos resultados con la herramienta K6 que corres sobre Javascript (https://k6.io/docs/es/guias-de-prueba/pruebas-de-carga-para-apis/).

Se avanzo en el informe de resultados de pruebas: https://docs.google.com/document/d/1VLgJTM_CJTgrRVTSUKH81KUH4a3Apt7Ans_PhEXXtk0/edit?usp=sharing

**Comment by ManuelStardust** [comment]
Se realizaron nuevas pruebas de carga sobre el servidor de AWS y se actualizo el informe de rendimiento con estos resultados. https://docs.google.com/document/d/1VLgJTM_CJTgrRVTSUKH81KUH4a3Apt7Ans_PhEXXtk0/edit?usp=sharing

Se cargaron los scripts para K6 en el drive de la herramienta web https://drive.google.com/drive/folders/1INkF7cJf5mdgA0DGT7YHFAd0xWY38oZv?usp=sharing
