### ISSUE TITLE
Preparar documento sobre arquitectura de la herramienta

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#215]
El miércoles 27 se tiene una reunión con el equipo de tecnología de ecopetrol para discutir la transferencia de la herramienta, nos pidieron tener la siguiente información lista para explicárselas, todo enfocado a dejar claridad sobre la arquitectura, la comunicación entre componentes y los servicios disponibles:

- Entradas y salidas de cada endpoint
- Descripción de los componentes de la herramienta, haciendo énfasis en el del simulador, con las dependencias que tiene cada uno.
- Explicar cómo conecta el servidor todos los componentes de la herramienta.

**Comment by erikasv** [comment]
@ManuelStardust aquí está el [documento](https://docs.google.com/document/d/1ADcVbdBqEx3DMO-kGuRC4_raRP7DCLPtFJFtD7gt2R8/edit#) requerido, por favor revisarlo y dejar comentarios con lo que falte o no esté claro

**Comment by ManuelStardust** [comment]
El documento cuenta con la finrmación completa, se recomienda agregar el diagrama de la arquitectura ya existente.
