### ISSUE TITLE
Hacer plan para migración de Ceiba

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#219]
# Descripción

Hacer un plan para migrar producción de ceiba, tener en cuenta lo siguiente:

- Que los backups sigan funcionando
- Que el script de elastic search siga funcionanado
- _**Un plan B** para hacer rollback en caso de que algo falle en el proceso_
- Si se necesita ayuda de varias personas
- Requerimientos de instalación y otros detalles necesarios para la nueva versión (por ejemplo, el caso de la versión de docker)

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/219?planning-poker) with ZenHub @Trjegul84

**Comment by Trjegul84** [comment]
Se inició un [documento](https://docs.google.com/document/d/1LvT5o1k1EF6yHqK0kgs74_w6RHX4CTL580gOs-Oz9oY/edit?usp=sharing) donde se registran las consideraciones y pasos necesarios para realizar la mgiración.

**Comment by Trjegul84** [comment]
Se realizó una revisión detallada del backup de ceiba y se observa en el log del script que la ultima vez que este fue realizado con éxito y con el peso completo fue el 04 de Julio de 2022 y a partir del siguiente día los backups se encuentran incompletos, algunas veces copia unos recursos otras veces copia otros pero el peso final de los backups siempre oscila en los 126M y la carpeta de recursos de producción pesa 2.3 G.

El mensaje de error que se muestra en el log de errores del scrip es `"failed: No space left on device"`

**Comment by Trjegul84** [comment]
Se sacó un backup manual de los recursos de producción a la fecha de 3 de Agosto y se creó el bucket `backup-resources-ceiba` en S3 para guardar toda la carpeta de recursos en el archivo `backupCeiba-03-08-2022.tar.gz`
