### ISSUE TITLE
Construir los requerimientos a partir de las historias de usuario

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#22]
A partir de las reuniones e información recopilada, construir el listado de requerimientos iniciales para la herramienta web a formular en FIBRAS

**Comment by alegnaaived** [comment]
[En la carpeta](https://drive.google.com/drive/folders/1qAcSczW5Xn10a1802Y04vNIcN9TXAG1q?usp=sharing) con el contenido de los avances de este año, se encuentra [el documento de entrega](https://docs.google.com/document/d/1NywwhlSG99JJtMOJRwrd_Lv8zZv50OHzzqLs2dwk0ao/edit?usp=sharing) que contiene los usuarios, roles y un primer listado de funcionalidades identificadas.

Las últimas reuniones realizadas fueron:
 - "FIBRAS-ECOPETROL - Sobre simulación de escenarios". Jueves, 8 de octubre. 9am a 10am. Con Jorge Amador
 - "Funcionamiento de ECOGIS - Convenio Ecopetrol Humboldt". Lunes, 19 de octubre⋅9:00 – 10:00am. A través de MicrosoftTeams, liderada por ECOPETROL.

**Comment by danflop** [comment]
El resultado de esta tarea se verá modificado debido a cambios en la orientación de la herramienta. Estos nuevos requerimientos estarán en otra tarea.
