### ISSUE TITLE
Cambios en interfaz gráfica de Ceiba v.2

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#223]
Se debe coordinar con diseñador reunión para definir los cambios que se realizarán a la interfaz de Ceiba v.2
Identificar los archivos que se intervienen en estos cambios y crear tarea(s) para implementarlos

Adicionalmente se debe actualizar el ambiente de aws para que César pueda ver los cambios previamente realizados.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/223?planning-poker) with ZenHub @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se trabajó en equipo con el diseñador y se logró identificar directamente en los archivos css y ftl necesarios para adecuar la interfaz de Ceiba v2.0. 
Se adelantaron cambios que se subieron a la rama `feature/customizeCeibaGUI` del repositorio en Github.

Queda pendiente navegar la plataforma con los cambios ya realizados e identificar cuales cambios faltan por realizar y agendar una nueva reunión.

**Comment by Trjegul84** [comment]
**Nota:**
No es posible clonar el repositorio de ceiba de gitlab desde la máquina de AWS, para hacer el despliegue en un servidor fuera de la infraestructura institucional es necesario copiar los archivos manualmente al servidor de la nube.
