### ISSUE TITLE
Preparar diapositivas para la presentación de la herramienta a ecopetrol

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#238]
# Descripción

Preparar las diapositivas discutidas en la planeación del 23 para la presentación de la herramienta a ecopetrol.

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/238?planning-poker) with Zenhub @ManuelStardust

**Comment by ManuelStardust** [comment]
La presentación queda para revisión, una vez aprobadas las diapositivas se pasaran a la presentación general para el taller del 7 de octubre.

https://docs.google.com/presentation/d/13_PgAvt9KwPnEjj8dpRmnOTOQdTE4CrUXrOyeI9aXUg/edit?usp=sharing
