### ISSUE TITLE
Ajustes para despliegue de Ceiba v2.0

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#241]
Para la migración de Ceiba se requieren los últimos ajustes en los repositorios y archivos de docker:

- [x]  Actualizar el Readme del repositorio del ipt en Github
- [x]  Cambiar el titulo en inglés y corregir nombre de institución en formulario de metadatos
- [x]  Generar el .war con los últimos cambios en el código
- [x]  Agregar archivo `.dockerignore` para solucionar problema durante la creación de la imagen.
- [x]  Actualizar GitLab de Ceiba
- [x]  Instalar docker-compose en el servidor de la migración
- [x]  Solicitar que monten la unidad del backup de Ceiba en el nuevo servidor

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/241?planning-poker) with Zenhub @Trjegul84
