### ISSUE TITLE
Dockerizar el front del visor

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#245]
#Descripción

Se debe crear un Dockerfile, y si es necesario un docker-compose.yml, para desplegar el visor de la I2D en un contenedor de docker.

# Resultado
El visor ya no depende del tomcat donde esta ceiba actualmente y se puede desplegar en un cotenedor. 

# Consideraciones
Se puede tomar de referencia el portal de la i2d que también se dockerizó hace "relaivamente poco"

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/245?planning-poker) with Zenhub @danflop @ManuelStardust @Trjegul84

**Comment by Trjegul84** [comment]
Se creó un Dockerfile para el despliegue del visor en el nuevo servidor donde quedará alojado de esta forma se tendrá un contenedor apache para alojar el front del visor. 
El dockerfile puede ser revisado en el [PR](https://github.com/PEM-Humboldt/visor-geografico-I2D/pulls) del repositorio de Github.

**Comment by erikasv** [comment]
@Trjegul84 Podrías por favor actualizar las instrucciones generales de despliegue del repositorio de [gitlab](http://192.168.11.78/pem/visor_geografico)
