### ISSUE TITLE
Revisar GeoServer del visor

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#247]
# Actualización 28/11
Hoy se ha caído el servicio. De manera que se le debe dar prioridad a esta tarea y restaurar el servicio.

Dar prioridad a por qué se cayo esta última vez.

# Actualización 18/10

Sigue faltando revisar ventanas de tiempo específico y determinar si hay algún problema adicional.

**Revisar en el período de tiempo en el que ocurrió la caída detectada por uptimerobot**

# Descripción

Revisar los logs del GeoServer cerca a las ventanas de tiempo en las que Carolina ha reportado que el servicio deja de funcionar.

Adicionalmente se debe agregar la url al monitoreo de uptimeRobot.

# Resultado

Diagnosticar si se requiere ampliar la máquina o si los errores se han debido a otra cosa.

**Comment by ManuelStardust** [comment]
El log de errores arroja lo siguiente: 

05 Oct 21:08:32 ERROR [memory.MemoryBlobStore] - /opt/geoserver/data_dir/gwc/tmp/cec0c6ca-0092-4f59-850d-4f430e9bebef (No space left on device) for /opt/geoserver/data_dir/gwc/Proyecto_fondo_adaptacion_Humedales_Continentales_Insulares_2015_Vector/EPSG_900913_13/018_033/002410_004261.png
org.geowebcache.storage.StorageException: /opt/geoserver/data_dir/gwc/tmp/cec0c6ca-0092-4f59-850d-4f430e9bebef (No space left on device) for /opt/geoserver/data_dir/gwc/Proyecto_fondo_adaptacion_Humedales_Continentales_Insulares_2015_Vector/EPSG_900913_13/018_033/002410_004261.png

Al comprobar el espacio en disco se encuentra que la unidad no cuenta con espacio disponible.
/dev/nvme0n1p1    60G    60G   20K 100% /

**Comment by ManuelStardust** [comment]
Se realizó una revisión de los logs de Geoserver y Tomcat, así como del estado del servicio de Geoserver.

[Revisión de Logs Servidor GeoServer](https://docs.google.com/document/d/16pwi0e_v_0okknft55VZiGyhyUS3sTeArE81VslGSuw/edit?usp=share_link)
