### ISSUE TITLE
Preparar despliegue de contenedores en nueva máquina de Ceiba

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#248]
# Descripción

Preparar los archivos necesarios para el despliegue del visor y de ceiba en el nuevo servidor, esta tarea incluye:

- Crear docker compose que se encargue de levantar proxy, visor y ceiba.
- Crear archivo de configuración para el proxy, puede basarse en el de GeoNetwork o el de BioTablero
- Versionar los archivos previos (y los demás que se puedan generar) en el repositorio de gitlab del visor (ver consideraciones para contemplar versionarlo en el repo de Ceiba), agregar las instrucciones de uso de los mismos y agregar un enlace en el readme del repositorio de gitlab de Ceiba.

# Resultado
Archivos que permitan desplegar los contenedores de la forma más automática posible en el nuevo servidor cuando se realice la migración de Ceiba

# Consideraciones
- Los tres contenedores deben quedar en la misma red (configurar una en el archivo docker-compose)
- Ya que Ceiba tiene su propio docker-compose, valdría la pena verificar si es mejor simplemente agregar a éste los contenedores del visor y del proxy

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/248?planning-poker) with Zenhub @Trjegul84 @danflop

**Comment by Trjegul84** [comment]
Se creó un docker compose para que funcionen las dos aplicaciones visor-I2D y Ceiba v2 en la misma red de contenedores. El archivo se llama docker-compose-proxy. 
Se creó el archivo de configuración de nginx para que direccion de igual forma que esta actualmente producción.

Problema:
Se realizaron varios intentos del despliegue con el docker-compose-proxy.yml y logra desplegar el visoi I2D sin embargo, no se logra desplegar Ceiba con exito, se presenta el siguiente error al ser desplegado de forma independiente o a través del proxy:

```
FreeMarker template error (HTML_DEBUG mode; use RETHROW in production!)


The following has evaluated to null or missing:
==> baseURL  [in template "WEB-INF/pages/inc/header.ftl" at line 14, column 52]

----
Se identifica que este problema es debido a que en el contenedor no se crean los archivos ipt.properties y los otros archivos de configuración que deben crearse la primera vez que se lanza el servidor. 
Se prueba replicando el mismo ambiente de despliegue en AWS y allá si funciona.

**Comment by erikasv** [comment]
Daniel sugiere probar desplegando en otro servidor y verificar si funciona, en este caso se solicitará a tecnologías que cambien el sistema operativo del 74
