### ISSUE TITLE
Spike: Revisión NADA

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#25]
Revisión de la documentación para despliegue, revisión si hay docker y si no trabajar en el docker file para despliegue en algún servidor del instituto o en AWS

**Comment by Trjegul84** [comment]
Se creó una nueva instancia EC2 en AWS. La maquina Centos 7 se llama Nada-centos, en esta se instala y configura la plataforma NADA. Se documenta el proceso en el documento ubicado en la carpeta de la I2D/Socioecologio del drive.

[Instrucciones instalación NADA](https://docs.google.com/document/d/1ip2xU3UZkEkKILuICuz5fJYjxpCdfshEnGZHM7m9H0A/edit?usp=sharing)

**Comment by Trjegul84** [comment]
Se envió correo a personal de la I2D con las credenciales de acceso a NADA.

**Comment by Trjegul84** [comment]
Se presenta error en el formulario de agregar estudio mediante el botón Add Study, 

> "La carpeta de destino de la subida no parece escribible"

Se pidió ayuda a los desarrolladores de NADA y  parece que la configuración de permisos es correcta. Se prueba la carga de estudios con la opción Bulk Import DDI y con esta se cargan los archivos a plataforma de forma correcta y sin errores.

**Comment by Trjegul84** [comment]
Se envió correo a Diego Randolf comunicando la opción para cargar archivos de estudios y se llego al acuerdo de continuar las pruebas de la plataforma con el uso de opción de Bulk Import DDI.  El continuará con las pruebas y si llega a existir otro error y/o sea necesario contactar al personal de DANE se continuará con el proceso de revisión.
