### ISSUE TITLE
Alerta de Port Scanning desde la Instancia EC2 de Dataverse

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#253]
Se recibió un mensaje de alerta que pueden consultar en el Dashboard de AWS Health Dashboard. El mensaje se puede consultar aquí: [Alerta](https://docs.google.com/document/d/1ZhuxKHg9Ncp533biUTE4pCC7H3ptPjX13fZSp5FXmfY/edit?usp=sharing).

El objetivo es revisar si el tráfico anormal que está saliendo de la máquina se debe al servicio DOI o si la instancia se encuentra comprometida.

**Comment by erikasv** [comment]
@danflop @Trjegul84 dejé comentado lo que pasó en el documento con el reporte
