### ISSUE TITLE
Despliegue de Ceiba v2 en el datacenter

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#255]
# Actualización 21/11

Tener en cuenta que las últimas modificaciones al visor queden en el nuevo despliegue y que su funcionamiento es correcto.

# Descripción
No se ha logrado el despliegue exitoso de Ceiba v2 en el datacenter.

Se cargaron los archivos docker-compose y Dockerfile necesarios para la dockerización tanto del visor-I2D como de Ceiba v2 y usando nginx para re-direccionar correctamente. Esta dockerización solo funcionó para el visor pero falla para Ceiba v2. 
Se ha probado esta dockerización de forma local y en el servidor de amazon y si funciona pero no funciona en las máquinas .74 y .43 de la infraestructura. 
Los últimos intentos consistieron en instalar tomcat 8/9 y Java 9 desplegar sin dockerizar pero se despliega con errores o los errores se generan una vez se copia los recursos a la carpeta correspondiente. 

Problemas: 
A. Si logra la ejecución de Ceiba v.2:
1. Sale un warning y no salen las opciones en el select tipo cuando se crea un recurso. 
![Screenshot_20221108_085500.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/b4b7eafe-54cb-4b6f-aaa7-3c30ea083d90)

2. Al ingresar a la sección de Administración >> Opciones del ipt 
![Screenshot_20221108_085714.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/b05c8d49-e0c9-46a8-8e5f-9a7398b65cd5)

B. Si no se logra la ejecución, inmediatamente se despliega por docker o sin docker se presenta el siguiente error sin dar opción a ingresar a la configuración o ninguna otra parte de la plataforma.
![Screenshot_20221024_162220.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/8bb2a66b-b5fb-4c69-ac4e-4b44a5112228)

**Comment by erikasv** [comment]
Al terminar el sprint seguíamos sin contar con el volumen en el 74

**Comment by erikasv** [comment]
Se ha desplegado exitosamente ceiba y el visor en contenedores en el 74, al momento de hacer la migración tener en cuenta:

- Dejar funcionando los cronjobs de backups, ya no es necesario tener backup del código
- Dejar funcionando el cronjob para indexación de elasticsearch

**Comment by Trjegul84** [comment]
Para que funcione la instalación en el servidor del datacenter fue necesario que TI creara la máquina por fuera del grupo del host y luego la una de nuevo. Sin este proceso no se logra un adecuado funcionamiento de los volumes de docker.
