### ISSUE TITLE
Limpiar máquina de dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#256]
# Descripción y resultado
Limpiar la máquina de dataverse (idealmente reinstalar, recrear o restaurar en un punto anterior donde no estaba comprometida)

Tener cuidado de no perder los datos.

Al restaurar el funcionamiento de la misma, cuidar los puertos que se dejan abiertos, cambiar puertos y contraseñas por defecto y usar contraseñas seguras.

**Comment by Trjegul84** [comment]
Se intenta instalar la versión anterior de Dataverse (5.5)  en una máquina centos 7.9 pero se presentaron diferentes problemas de la compatibilidad de versiones de R para esta versión y de solr. 
Se intenta instalar la versión 5.6 en una nueva máquina centos 7.9  pero se presentan problemas durante la instalación de R, aunque se logra completar la instalación la migración (pg_restore) de la base de datos falla.  También se intentó instalar R(versión > 4) con centos 8 pero esta distribución requiere una afiliación de la infraestructura del instituto al Red Hat subscription management service y seleccionar un plan de soporte para obtener las credenciales necesarias para instalar R y otros paquetes. Por esta razón se desiste de usar Centos 8. 

Se logra instalar la versión 5.12 de Dataverse sin mayores inconvenientes, esta vez usando una máquina Rocky Linux, en esta versión no es posible migrar la base de datos debido a incompatibilidad de varios campos y del esquema modificado mediante las actualizaciones, para esto existe un script para ir realizando la migración progresiva por cada versión y este proceso es complejo y toma más tiempo. 
Dataverse se encuentra funcional en la ultima versión y con se puede instalar mediante los pasos de la guía normal pero hay que instalar openssl y curl como pasos adicionales para que funcione R.
