### ISSUE TITLE
Desplegar nueva versión de Dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#259]
# Descripción y resultado

Debido a las complicaciones en la tarea [256](https://github.com/PEM-Humboldt/dev-scrum/issues/256) se ha decidido desplegar al nueva versión de dataverse en lugar de intentar replicar la que teníamos anteriormente

# Actualización Dic 5

Se debe documentar la nueva máquina en el gitlab

**Comment by Trjegul84** [comment]
Se logró instalar de forma exitosa la versión 5.12.1 de Dataverse, en una máquina nueva con SO diferente y que permitió la instalación de la version R compatible y sus respectivas extensiones.
