### ISSUE TITLE
Spike: Revisión Dataverse

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#26]
Revisión de la documentación para despliegue, revisión si hay docker y si no trabajar en el docker file para despliegue en algún servidor del instituto o en AWS

**Comment by cazapatamar** [comment]
[Documento con las instrucciones](https://docs.google.com/document/d/1-qg6ZRIzdd8OYSBVWgIY0CLPT2fWO4_xUofX-myCeLE/edit)

**Comment by cazapatamar** [comment]
[Docker](https://hub.docker.com/r/ndslabs/dataverse) no oficial cuya última actualización fue en el 2018

**Comment by cazapatamar** [comment]
Se deplegó de manera local con éxito, salvo algunas configuraciones posteriores que toca tener en cuenta en un ambiente de producción (usurio con el que se instala, password admin de postgres, SMTP, etc)

[Documento con las instrucciones de instalación para la versión 5.1 en CentOS 7](https://docs.google.com/document/d/1-qg6ZRIzdd8OYSBVWgIY0CLPT2fWO4_xUofX-myCeLE/edit)
