### ISSUE TITLE
Revisar errores de Ceiba

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#261]
# Descripción y resultado

Revisar y corregir los siguientes errores de Ceiba: 

- [x]  Error cuando se colocan saltos de línea en la financiación del proyecto
- [ ]  Error en ftl de nuevo recurso (este se ve varias veces en los logs)

**Comment by Trjegul84** [comment]
Se arregló el problema de los errores de línea, queda el código del .war en producción con esa actualización pero el repositorio de GitHub aún tiene un PR pendiente para mezclar los cambios y que queden en la rama `ceiba_master`.

**Comment by erikasv** [comment]
El error del ftl en nuevos recursos no afecta el funcionamiento, se retomará cuando se reporte un problema o cuando alguien nuevo pueda revisarlo
