### ISSUE TITLE
Sacar ediciones y calificaciones de BioModelos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#266]
# Desccripción y resultado

Carlos Jair solicitó la información de calificaciones de aves y las ediciones de epifitas. Daniel hacía esto antes y tenía un script para eso, buscarlo y entregar los datos.

Idealmente estos scripts deberían integrarse en [biomodelos-db-utils](https://github.com/PEM-Humboldt/biomodelos-db-utils)

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/266?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by cazapatamar** [comment]
Revisado y probado con @ManuelStardust
