### ISSUE TITLE
Acordar metodología para seguimiento de la carga según estimación y horas reales invertidas

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#27]
Conocer los puntos de historia promedio de un integrante del equipo para asignación en la planeación.

Revisión de herramienta o extensión para monitoreo y/o cálculo de este indicador.

**Comment by erikasv** [comment]
Un poco de actualización sobre esta tarea:

Zenhub calcula la velocidad del equipo completo (incluyendo lo esperado y lo realizado). Ya que scrum es una metodología que ve al equipo como un todo, no creo que vayamos a encontrar una herramienta que permita analizar a cada integrante.

A pesar de que el análisis por miembro alcanza a caer un poco en micromanagement (que no es algo que en realidad queramos), sí resulta importante conocer la capacidad de carga de cada uno.

Por ahora hemos llevado registro en una hoja de cálculo dónde registramos las horas estimadas y las horas reales que tomó cada tarea, pero no es la solución ideal, pues pasa que se olvida registrar horas, o tareas, y no permite analizar el carryover

**Comment by erikasv** [comment]
Desde hace algún tiempo se dejó de llevar el registro en la hoja de cálculo
