### ISSUE TITLE
Desplegar dataverse en AWS

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#28]
Desplegar dataverse en AWS siguiendo las instrucciones del [documento](https://docs.google.com/document/d/1-qg6ZRIzdd8OYSBVWgIY0CLPT2fWO4_xUofX-myCeLE/edit#heading=h.bwhqgmqcvwb)

**Comment by cazapatamar** [comment]
@Trjegul84 Realiza el despliegue en AWS y se deja en una maquina EC2. Por el momento se dejará apagada la maquina y se configurará de nuevo el acceso a dataverse (haciendo el undeploy y nuevamente el deploy por el cambio de ip) cuando Diego pueda revisar la herramienta.

Se cierra tarea ya que se complió el objetivo incial de desplegar dataverse en AWS

**Comment by Trjegul84** [comment]
Instacia EC2 t3.medium Dataverse 
Queda pendiente la reconfiguración de la IP fija una vez se vuelva a encender la máquina.
