### ISSUE TITLE
Geonetwork - Ajustar scripts de backups

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#281]
De acuerdo a lo encontrado en esta [tarea](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/gh/pem-humboldt/dev-scrum/274), hacer los siguientes cambios:

- Cambiar los scripts para que empiecen a hacer el backup semanalmente y haya retención de 2 meses (tener cuidado al hacer los cálculos)
- Actualizar la documentación de gitlab para que queden al día los scripts y la aclaración que el script de backups debe quedar en los jobs del root

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/281?planning-poker) with Zenhub @hacheG @ManuelStardust

**Comment by erikasv** [comment]
@cazapatamar @ManuelStardust por favor voten esta tarea

**Comment by erikasv** [comment]
Se realizó el cambio en el script de backups y en el cron para ejecutarlo todos los viernes

**Comment by erikasv** [comment]
Siguen habiendo problemas de espacio, pero se ejecutó corretamente
