### ISSUE TITLE
Reunión y documento de administración de aplicaciones I2D

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#39]
Realizar un documento con las instrucciones básicas para administrar los contenedores de las aplicaciones I2D, especialmente Geoserver y Geonetwork. Especificar datos de ubicación e instrucciones básicas para arrancar, parar, reiniciar los contenedores.

Reunión con Liceth para socializar el documento

**Comment by erikasv** [comment]
Pongo esto en ready para determinar si aún es necesario hacer el documento (en este caso verificar si hay algo parecido ya en otra parte) o si simplemente cerramos la tarea
