### ISSUE TITLE
Desarrollo de taller de priorización de funcionalidades Ecopetrol

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#46]
- [ ] Elaborar la dinámica para la ejecución del taller interno de manera que mediante la discusión se puedan obtener unas funcionalidades priorizadas que respondan a las necesidades de los usuarios y al alcance del equipo de desarrollo Humboldt.
- [ ] Liderar el taller.

**Comment by alegnaaived** [comment]
Definir qué datos se manejarán y acordar el alcance de la herramienta web

**Comment by alegnaaived** [comment]
Se realizó la actividad con el equipo del componente 2, pero no estaba Maria C. Se propuso durante la reunión que se realice una nueva reunión con Maria C y Julián (porque está trabajando en el componente 3).

[Enlace a la presentación que se realizó](https://drive.google.com/file/d/19eJWL4y1_xNyH6Au_X4rW5RKU3g_zSVd/view?usp=sharing)

**Comment by alegnaaived** [comment]
Para una nueva tarea para continuar esta labor, corresponde a agrupar los requerimientos para presentar a ECOPETROL junto con las funcionalidades seleccionadas con Maria C en reunión con @danflop (ya socializada)
