### ISSUE TITLE
Spike: Revisión de políticas y estado de backups para las diferentes aplicaciones del PEM

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#48]
Revisar el documento de las políticas de backup de las diferentes bases de datos y aplicaciones administradas por nosotros. Para esto, utilizar el siguiente documento como guía: 

[Documento políticas backups PEM](https://drive.google.com/open?id=13-uP-t_bkim1NVaGKxkmbscavY0xVMOX)

A partir de este documento :

- [ ] Revisar el estado actual de cada uno de los backups (verificar que se esté ejecutando, verificar la fecha del último que se tiene para cada uno).
- [ ] Identificar los backups que estén haciendo falta y que no se encuentren referenciados en el documento.

**Comment by alegnaaived** [comment]
Realizamos listado para revisar los servidores y nos dividimos las revisiones https://docs.google.com/spreadsheets/d/1ZSEANyBEWOUurp3Um2KZtiwH2ttEbQ0cFysgk8JTqqI/edit?usp=sharing

**Comment by Trjegul84** [comment]
Se finalizaron las revisiones de cada uno de los servidores y sus aplicaciones correspondientes. 

Se distribuyo la revisión de los backups de servidores de la siguiente forma:

Angela Devia: 
- 192.168.11.42 / 63 / 78 / 35 / 82 / 70 
Angela Checa:
- 192.168.11.59 / 105 / 106 / 60  / 58

Se programará una reunión para la exponer los resultados de esta tarea y se creará una nueva tarea para las actividades derivadas y pasos a seguir.
