### ISSUE TITLE
Unión y siguientes pasos a partir de revisión de resultados de las políticas de backup

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#51]
Angela Devia y Angela Checa realizaron una revisión de los servidores a cargo del PEM en la tarea [48](https://github.com/PEM-Humboldt/dev-scrum/issues/48)

Esta tarea es para resolver dudas con Daniel, algunas como:
- Sobre servidores donde no se tiene claro nuestra administración (del equipo)
- Sobre aplicaciones que pueden no seguir vigentes

Ya se identificaron las siguientes tareas (crear issues una vez aclaradas las dudas) - confirmar en la sesión con Daniel:
- Eliminar aplicaciones
- Estandarizar la gestión de backups 
- Documentar las políticas de backups
- Creación de scripts para backups
- Posible eliminación de aplicaciones obsoletas

En caso de ser necesario se realizará una sesión con todo el equipo.

**Comment by Trjegul84** [comment]
Se efectuó reunión de socialización del diagnostico inicial de los servidores y se establecieron actividades por realizar para cada caso.
Se acuerda crear un nuevo esquema para el documento de inventario de backups y aplicaciones que incluya ip, puerto tipo, nombre de contenedor, tipo de recurso, entre otros. 
Se debe profundizar las revisiones y agregarlas al documento con el nuevo esquema.

**Comment by erikasv** [comment]
Se creó una tarea con los siguientes pasos.
