### ISSUE TITLE
Implementar control de acceso a recursos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#54]
Es el cambio más importante que se debe realizar en la personalización del IPT, consiste en agregar un control sobre los datos almacenados para el acceso a la descarga de los mismos.

Documentado [aqui](https://docs.google.com/document/d/1E2-77t0zLwtQbYb9eRmZ7ctFDQJKDWKAgBgB51p7XBI/edit#bookmark=id.fmluofckfn9d)

**Comment by alegnaaived** [comment]
Se realizó hasta el commit 13 del historia de IPT-CEIBA en la nueva versión del IPT que es 2.5.0, pero requerimos validar estos cambios con Carolina y Juan, para verificar que las funcionalidades sí validen la información como se espera.

La reunión quedó programada para la próxima semana.

**Comment by Trjegul84** [comment]
Tareas para continuar con la migración:

1. Revisar si la búsqueda esta en IPT no test (producción)
2. Revisar si configurando algo aparece el icono de búsqueda
3. Si aparece el icono de búsqueda si esta sirve para reemplazar el elastic search
4. Revisar si necesitamos mas commits
5. Verificar como validar la compatibilidad de versiones de jQuery, bootstap y multiselector (Prioridad alta)
6. Revisar el error de user.ftl  (Prioridad alta)
7. Verificar porque no carga la vista de edición de usuario (Prioridad alta)
8. Crear mas usuarios y verificar la asignación de permisos

**Comment by Trjegul84** [comment]
Respecto a las tareas anteriormente listadas se encontró:

(1.) Revisar si la búsqueda esta en IPT no test (producción):  No se encuentra en el ipt de Gbif (producción) en Ceiba de I2D se creo en el commit 16 del 29 de mayo de 2016.

(2.) Revisar si configurando algo aparece el icono de búsqueda: No se debe configurar nada, se debe implementar.

(6.) Revisar el error de user.ftl (Prioridad alta): Se arreglo este error pero la acción de dar acceso a los recursos no se esta ejecutando.

(7.) Verificar porque no carga la vista de edición de usuario (Prioridad alta): Se arreglo esta vista y ya se puede editar usuario pero sigue sin funcionar la parte de los permisos. 

(8.) Se realizaron pruebas de creación de usuarios de los diferentes roles:
Usuario	  
Administrador sin derechos de registro
Administrador con derechos de registro
Administrador  
A cada usuario se asignaron permisos de acceso a algún recurso mediante el botón de la interfaz de administración de recursos y esto no tiene efecto alguno. Los usuarios solo pueden ver los recursos que crearon y aunque se les asigne el permiso este no tiene efecto y sigue observando los mismos recursos. (Se debe revisar más a fondo el código para encontrar el problema). 

_**Revisar**_: 
- _UserAccountManagerImpl.java_ que enlaza con _users.xml_
- Volver a revisar la lógica del archivo _resource_new.ftl_  y denuevo comparar con _resoruce.ftl_ de Ceiba.

**Comment by Trjegul84** [comment]
Se realizaron pruebas de nuevo y se verifica que si se están asignando los recursos pero en la interfaz de usuario cuando se requiere asginar los permisos en lote, los permisos no se cargan en la interfaz y no no pueden asginarse.

**Comment by danflop** [comment]
A partir de esta tarea se generan las siguientes: #70, #71, #72, #73
