### ISSUE TITLE
Modificaciones sección general

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#56]
Agrupa las siguientes modificaciones:
- Eliminar conexión a GBIF
- Agregar conexión con el portal I2D
- Incluir tipo de acceso después del título

Estas modificaciones hacen referencia a [esta sección del documento](https://docs.google.com/document/d/1E2-77t0zLwtQbYb9eRmZ7ctFDQJKDWKAgBgB51p7XBI/edit#bookmark=id.fmluofckfn9d)

#### NOTA
Por favor, si consideran que alguna de estas modificaciones debería tener su propia tarea, agregar un comentario indicándolo y con gusto la separo.

**Comment by alegnaaived** [comment]
La ubicación del tipo de acceso se agregó en el [PR#19](https://github.com/PEM-Humboldt/ipt/pull/19) dado que corresponde al alcance del tipo de acceso a partir de la licencia I2D seleccionada.

**Comment by Trjegul84** [comment]
Las modificaciones de esta tarea ya fueron realizadas. 
La versión actual que se encuentra en staging no tiene conexión a Gbif porque está en un modo de prueba y en este modo no hay conexión entonces no fue necesario realizar modificaciones al código.
Ya esta visible el tipo de acceso después del título.
Falta confirmar con equipo a qué se refiere con agregar conexión con el portal I2D, porque según las explicaciones Ceiba es independiente.
