### ISSUE TITLE
Modificar íconos de ayuda para los campos de la herramienta

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#57]
Cambio documentado en sección [Página edición de metadatos](https://docs.google.com/document/d/1E2-77t0zLwtQbYb9eRmZ7ctFDQJKDWKAgBgB51p7XBI/edit#bookmark=id.o1h87jqduln2)

**Comment by Trjegul84** [comment]
Esta tarea ya se realizó en el [commit](https://github.com/PEM-Humboldt/ipt/pull/30/commits/d8510d3a151e53a78df83d364e3aa1615dd07ff3)
