### ISSUE TITLE
Actualización de documento y siguientes pasos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#59]
En la tarea [51](https://github.com/PEM-Humboldt/dev-scrum/issues/51) se realizó la socialización sobre los backups, en dicha reunión quedó pendiente la actualización del documento que condensaba la información.

En esta tarea se espera realizar dicha actualización y crear las tareas necesarias para los siguientes pasos.

#### Consideraciones
No es necesario hacer las actualizaciones mencionadas en el documento de servidores.

**Comment by alegnaaived** [comment]
Se realizó una propuesta de documento para el [Inventario de servidores y de aplicaciones](https://docs.google.com/spreadsheets/d/1zzfVGjSrWLbGRnFBhXwuUQ9MPAajTuRcHqKtaUygCzM/edit?usp=sharing) que fue revisada en el daily del 24 de junio.

Las próximas tareas a realizar al diligenciar el [Inventario de servidores y de aplicaciones](https://docs.google.com/spreadsheets/d/1zzfVGjSrWLbGRnFBhXwuUQ9MPAajTuRcHqKtaUygCzM/edit?usp=sharing) son:
 - Migrar la información que está en el documento de diagnóstico hecho en la tarea [51](https://github.com/PEM-Humboldt/dev-scrum/issues/51) 
 - Ingresar a cada servidor para identificar contenedores, imágenes, validar versiones de sistema operativo y de docker, y verificar unidades montadas en el servidor y en cada docker
 - Realizar reunión de socialización de los resultados para evaluar los siguentes pasos
