### ISSUE TITLE
Revisión de los repositorios del equipo de ecoacustica

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#6]
Revisar los repositorios del equipo de electroacústica y tomar nota de recomendaciones o correcciones a hacer para cuadrar una reunión con Juan

**Comment by alegnaaived** [comment]
Pregunta:
1. ¿README en inglés o en español?
 - En Inglés: [https://github.com/PEM-Humboldt/format_ml_dataset/blob/master/README.md](https://github.com/PEM-Humboldt/format_ml_dataset/blob/master/README.md), [https://github.com/PEM-Humboldt/soundclim](https://github.com/PEM-Humboldt/soundclim)
 - En Español: [https://github.com/PEM-Humboldt/ecoacoustics_eda](https://github.com/PEM-Humboldt/ecoacoustics_eda)

Consejos sobre [https://github.com/PEM-Humboldt/format_ml_dataset](https://github.com/PEM-Humboldt/format_ml_dataset/blob/master/README.md)
[--> Empezar con un texto como: "Load /scripts/format_ml_dataset.ipynb in your preferred Jupyter Notebook or Python interpreter". Then, follow the instructions to load each file and format it as a Dataset for Machine Learning.](https://github.com/PEM-Humboldt/format_ml_dataset#getting-started)
--> Indicar cuál es el archivo específico a ejecutar. Pareciera que los otros archivos dentro de la carpeta scripts fueran versiones previas al notebook que se tradujo para el README.md
[--> "Segundosundos" or "Segundos"](https://github.com/PEM-Humboldt/format_ml_dataset#1-load-libraries-and-functions )
[--> Considerar cambiar el nivel del texto para entender el objetivo del repositorio después de cargar los archivos para iniciar](https://github.com/PEM-Humboldt/format_ml_dataset#audio-files)
[--> Se asume que este archivo es un template, pero como no es visible en el visualizador de Github, ¿qué se puede sugerir para que se tenga en cuenta como template?](https://github.com/PEM-Humboldt/format_ml_dataset/blob/master/scripts/.ipynb_checkpoints/format_ml_dataset-checkpoint.ipynb)

Consejos sobre [https://github.com/PEM-Humboldt/soundclim](https://github.com/PEM-Humboldt/soundclim)
--> Falta prerrequisitos (indicando que se requiere Python y R), autor(es) y licencia

Consejos sobre [https://github.com/PEM-Humboldt/ecoacoustics_eda](https://github.com/PEM-Humboldt/ecoacoustics_eda)
--> No es clara la estructura del README.md más allá del título y contenido del proyecto
--> Falta prerrequisitos (indicando que se requiere Python y R), autor(es) y licencia

**Comment by alegnaaived** [comment]
Recopilación de sugerencias del Daily:
--> Dependencias
--> Ejecución / Despliegue del contenido del proyecto
--> Orden para ejecutar el contenido de los repositorios, desde una vista de un usuario que nunca ha trabajado con este proyecto y que permita entender cómo empezar a utilizar los archivos.
