### ISSUE TITLE
Ajustes finales de diseño en nuevo IPT

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#60]
Agrupa las siguientes modificaciones:
- Cambiar Logo de Ceiba según indicaciones de Diseño mencionadas por Carolina Castro (nuevo [logo acá](https://sites.google.com/humboldt.org.co/i2dwiki/ceiba-manual/ceiba-incorporaci%C3%B3n?authuser=0) y preguntarle por el archivo vectorial entregado por el contratista)
- Ubicar el menú del header
- Ajustar estilos

Actualmente el IPT en migración no tiene el mismo estilo y requiere ajustes adicionales a los documentados en migraciones anteriores.

![image.png](https://images.zenhubusercontent.com/5af0bf174b5806bc2bd22104/a9c1cf51-3ad9-4440-91f7-d961a6624f29)

**Comment by alegnaaived** [comment]
El diseño que está en la rama master del repositorio de GBIF ha cambiado. Así que esta tarea puede implicar planeación en diseño del nuevo sitio web de CEIBA.

**Comment by erikasv** [comment]
No sé si se hicieron, pero este ipt ya está en producción
