### ISSUE TITLE
Verificar soporte de español en Dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#61]
Comprobar que toda la interfaz de Dataverse se pueda manejar en español.

En caso de que no tenga el idioma integrado por defecto, buscar si hay forma de ponerlo por medio de alguna extensión o algo de ese tipo.

**Comment by Trjegul84** [comment]
Debido a inconvenientes con durante la configuración del idioma fue necesario reinstalar Dataverse a su versión más reciente = 5.5
Se configuró el idioma Español para Dataverse mediante la rama **develop** del [Repositorio de Lenguajes de Dataverse](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs.git)
Se documentaron los  pasos para cargar idiomas en el documento de drive
[Comandos configurar idioma de Dataverse](https://docs.google.com/document/d/1DlBuDywSAkiqc_GJjFQQrs3LtqPR-RNngLwXMgHl5MU/edit?usp=sharing)

En la reunión de equipo el día de ayer 30 de Junio de 2021 se realizaron las siguientes actividades:
- Revisión de funcionalidad de lenguaje de la plataforma y las partes que no tienen traducciones.
- Pruebas iniciales de usuarios y sus diferentes roles. 
- Definición de nuevas tareas a realizar y se registraron en el documento de Ajustes funcionales.
