### ISSUE TITLE
Buscar causa y solución del error al hacer login en dataverse con usuario nuevo

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#62]
El objetivo es encontrar la causa y solución al error documentado en el punto [1](https://docs.google.com/document/d/1IgUlO4CXIqrNhMYzgW2r_RJ3Jl6l_p_Ta7qmeECkdRI/edit#bookmark=id.wnpixvjpcp78) de las revisiones.

Inicialmente pensamos que estaba relacionado con la siguiente descripción:
```
Parece que los usuarios de Dataverse sólo tienen acceso a las funcionalidades básicas cuando se selecciona la casilla de superusuario.

Entender la diferenciación de los roles, cuáles son los permisos de cada uno y qué efecto tiene en realidad esa casilla de superusuario.
```

Pero se ha acotado a que el error ocurre cuando se accede a la página inicial estando logueado con un usuario que no tiene rol (o cuando recién se loguea)

Tenemos algunas teorías de qué puede estar causando el problema:
- El usuario no ha verificado el correo
- No hay una página de inicio configurada => Esta se debe implementar de forma básica así no sea la solución al problema
- Falta configurar algo puntual para los usuarios sin rol

### Material
- Documentación de configuración [Custom Homepage](https://guides.dataverse.org/en/latest/installation/config.html#id91)

**Comment by cazapatamar** [comment]
Se realizaron las siguientes configuraciones pero hasta el momento no se ha encontrado la causa del error:

- Se configuró el homepage (página que se muestra al hacer login) tomando el template que está en la documentación
- Diego creó los roles que según su criterio aplican para el instituto asignándoles los permisos necesarios para cada caso. Se crearon usuarios de prueba y se asignaron los roles recién creados. Los roles creados quedaron especificados en este [documento](https://docs.google.com/spreadsheets/d/1N9ZNwDOlbsy6h6khMQTHGx1h9rwncPWUJC3g21yAJ6o/edit#gid=0).
- Se accedió a la base de datos, a través del cliente dbeaver desde el pc local, configurando temporalmente que la db reciba conexiones desde cualquier origen. 

Se exploraron las tablas relacionadas con la información de usuarios y se encontró que probablemente el campo por el cual se valida si un usuario ya validó su cuenta es `emailconfirmed` de la tabla `authenticateduser`. 

A manera de prueba, se registró un usuario, el cual queda sin roles. Luego, en la bd se asignó un valor en el campo `emailconfirmed` para simular que el usuario ya confirmó su cuenta. El resultado es el mismo, al hacer login con el usuario sigue saliendo el mensaje de error.

**Comment by cazapatamar** [comment]
Se publicó el dataverse root y se solucionó el inconveniente
