### ISSUE TITLE
Habilitar y configurar exportación de metadatos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#66]
El objetivo es entender cómo se almacenan los datos y habilitar y configurar la exportación de los metadatos.

Los metadatos se deben poder exportar a `DDI` y `Dublin Core`

Adicionalmente verificar que Dataverse tenga la opción de importar metadatos, en caso de que la exportación salga fácil y se puedan importar datos, habilitar la importación también.

**Comment by Trjegul84** [comment]
La documentación de Dataverse indica que solo cuando un conjunto de datos sea publicado este podrá  exportarse en una variedad de estándares y formatos de metadatos, que ayudan a que los conjuntos de datos sean más descubribles y utilizables en otros sistemas, como otros repositorios de datos. En la pestaña de metadatos de la página de cada conjunto de datos, están disponibles las siguientes exportaciones:

Dublin Core
DDI (Data Documentation Initiative Codebook 2.5)
DDI HTML Codebook (una versión HTML más legible de la exportación de metadatos DDI Codebook 2.5)
DataCite 4
JSON (formato nativo del software Dataverse)
OAI_ORE
OpenAIRE
Schema.org JSON-LD
Cada una de estas exportaciones de metadatos contiene los metadatos de la versión más reciente publicada del conjunto de datos.
En consecuencia es necesario realizar pruebas de publicación de datos con unos datos de prueba que sean candidatos a ser publicables. Esta prueba no se puede hacer con cualquier set de prueba porque en Dataverse los conjuntos de datos (datasets) publicados no pueden ser borrados solo se puede deshabilitar el acceso en caso de que sea legalmente necesario. Y existe una nota importante que alerta que el proceso deshabilitar un dataset es un asunto serio que puede incurrir en acciones legales y en que los datos no vuelvan a ser accesibles.  
Cuando los datasets son publicados cada cambio en sus metadatos o archivos se rastrea y se genera una nueva versión. 

Se acuerda en la reunión de equipo del día 6 de Julio/2021 que se debe considerar la prueba de publicación con unos datos que el equipo temático subirá a la plataforma. De igual forma se expone la necesidad de leer más sobre el funcionamiento del proceso de publicación de datasets y la relación existente con la plataforma DataCite, porque el instalador de Dataverse solicita los datos de acceso a una cuenta de [DataCite](https://datacite.org/) y no se tiene compresión de si esto afecte el proceso de publicación.

**Comment by Trjegul84** [comment]
Después de analizar la documentación  y realizar pruebas en reunión con el equipo de trabajo se encontró lo siguiente:

1. Para que funcione la pagina de inicio se debe publicar el Dataverse raíz (nombre del repositorio global), de esta forma los usuarios cuando acceden a la plataforma ven los datos de estadísticas del repositorio y no se presenta el error anteriormente documentado. La funcionalidad no esta relacionada con los roles de usuarios o algún tipo de configuración de estos.

2. Dataverse no deja publicar datasets mientras no se haya configurado el vínculo con una cuenta en DataCite, para generar DOIs persistentes. Para contar con cuenta en DataCite es necesario pagar una membresía de dos mil euros. Los datasets que publicamos en la prueba quedaron bloqueados hasta que se configure la cuenta de DataCite o Handle.net.
Una vez se publiquen los datasets o documentos esta herramienta generará un DOI persistente que permitirá al repositorio Dataverse de I2D conectarse con otras plataformas y certificar la proveniencia de los datos.

3. Se presenta un error  `"No se pudo grabar el rol - null" ` en la interfaz de administrador en el momento de editar los permisos de los diferentes usuarios ya existentes.

**Comment by Trjegul84** [comment]
Debido a la limitante del punto 2. Se espera a la respuesta de Sib Colombia sobre la cuenta en DataCite, y de lo que responda DataCite respecto a la creación de una cuenta de prueba. Una vez se cumpla este requerimiento se podrá continuar con las pruebas de publicación de datasets.

Quedan pendientes las siguientes tareas:
- Arreglar problema de carga de datos mediante archivo excel
- Arreglar error cuando el administrador edita permisos de usuarios
- Agregar configuración de correo electrónico y reenvío SMTP de la plataforma

**Comment by Trjegul84** [comment]
La opción de exportar archivos de en diferentes formatos se activa cuando se publican los Datasets.  Esta opción ya fue comprobada por Diego.

La configuración de SMTP para el envío de  correos desde la plataforma no es necesaria. Solo se requiere que desde la cuenta de administrador si es **gmail** se habilite el botón la opción de Configuración>>Seguridad>>Acceso de apps menos seguras, al habilitar ese acceso se permitirá que Dataverse pueda realizar el envío de correos sin restricción por parte de Google.

**Comment by Trjegul84** [comment]
Se encontró que para importar metadatos no hay opciones por interfaz sino por una funcionalidad llamada **importddi** del API de Dataverse.
Ejemplo: 
`curl -H X-Dataverse-key:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -X POST https://demo.dataverse.org/api/dataverses/root/datasets/:importddi?pid=doi:ZZ7/MOSEISLEYDB94&release=yes --upload-file ddi_dataset.xml`
