### ISSUE TITLE
Spike: Configuración de analytics para GeoNetwork

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#67]
Según explica Carolina Castro, GeoNetwork estuvo configurado con Google Analytics, pero esto se perdió con la migración que hicimos en 2019.

Se desea restablecer esta configuración. Buscar en el repositorio "antiguo" (o en otros) cómo se puede hacer esta configuración.

**Comment by danflop** [comment]
Se encontró el código de la versión 2.1.4 de GeoNetwork, y el archivo donde está incluida la referencia a google analytics es el siguiente:

/opt/tomcat/webapps/geonetwork_old/xsl/main.xsl


        <xsl:template match="/">
                <html>
                        <head>
                                <xsl:call-template name="header"/>
                                <xsl:apply-templates mode="script" select="/"/>

                                <style type="text/css">
                                        body {
                                                height:100%;
                                        }
                                </style>
                        </head>
                        <body onload="init();">
                                
                                <xsl:if test="not(/root/request/modal)">
                                        <div id="header">
                                                <xsl:call-template name="banner"/>
                                        </div>
                                </xsl:if>

                                <div id="content_container" style="display:none">
                                        <xsl:if test="/root/request/modal">
                                                <xsl:attribute name="style">display: block"</xsl:attribute>
                                        </xsl:if>
                                        <xsl:call-template name="content"/>
                                </div>

                                <xsl:if test="not(/root/request/modal)">
                                        <xsl:apply-templates mode="loading" select="/"/>
                                </xsl:if>

                <script>
                  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                  ga('create', 'XXXXX', 'auto');
                  ga('send', 'pageview');

        </script>
                        </body>
                </html>
        </xsl:template>

Este código se encuentra en el 11.70

Sin embargo, en versiones a partir de GN 3, se sugiere incluir el fragmento en la siguiente ubicación:

/var/lib/tomcat8/webapps/geonetwork/xslt/base-layout.xsl

Fuente: [http://osgeo-org.1560.x6.nabble.com/GN3-Google-analytics-td5299218.html](http://osgeo-org.1560.x6.nabble.com/GN3-Google-analytics-td5299218.html)
