### ISSUE TITLE
Spike: Agregar nueva plantilla al proyecto

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#70]
Se creó una nueva página pero no ha sido posible enlazarla a la plataforma para que sea accesible.

Se debe investigar cómo agregar estas nuevas plantillas a la plataforma (si requieren volver a compilar o qué otros pasos hay que seguir, por ejemplo)

**Comment by Trjegul84** [comment]
Se incluye lectura de fundamentos de freemaker disponible en:

[Freemaker quick start](https://freemarker.apache.org/docs/dgui_quickstart_basics.html)

**Comment by alegnaaived** [comment]
_Para esta demostración, se creó el archivo faq.flt_

El proceso para registrar una nueva página dentro del proyecto se debe:
 - Crear la página como archivo .ftl usando los estilos de bootstrap y ubicarlo en uno de los directorios ubicados en WEB-INF:
 ![image](https://user-images.githubusercontent.com/15584917/126815226-4b965d89-a536-40d0-bdc7-e66365a0de26.png)

 - Registrar la nueva página en el archivo struts.xml, indicando el nombre de la acción. Por ejemplo:
![image](https://user-images.githubusercontent.com/15584917/126815010-0b5b1eee-d495-4ffa-9d92-a6aaad7a0d02.png)
 - Siendo que el IPT utiliza los archivos .properties para llamar el contenido de las etiquetas, hay que verificar que esas etiquetas existen en el idioma actual. Para ello, se debe consultar en el archivo en español **ApplicationResources_es.properties** los valores de las etiquetas que se deben leer en el archivo .ftl creado:
 
![image](https://user-images.githubusercontent.com/15584917/126815721-5400baa2-c9a3-4341-a3b2-b4e085898131.png)
