### ISSUE TITLE
Revisar e identificar diferencias para migrar los metadatos de la versión 1.0.2 a la 1.1

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#71]
Revisar las diferencias que están generando errores o warnings para los diferentes metadatos de manera que se puedan aplicar a los metadatos de la versión antigua.

**Comment by Trjegul84** [comment]
Se realiza consulta con Carolina sobre diferencias en las características de los datos de los recursos que no cargan, por ejemplo:
acandi_arecaceae_2014
america_arecaceae_2014
le_cund_orquideas_2016
le_cund_orquideasnativas_2017
rrbb_cund_orquideas_2016
rrbb_cund_orquideas_2017
rrbb_cund_orquideasapco_2017
rrbb_cund_orquideasprio_2017

Se observa que la diferencia entre estos recursos y los que si cargan son los archivos  **dwca.zip** y todas sus versiones. Se aplica el mismo procedimiento de migración que ese efectuó con los otros recursos y en este caso no funciona.
