### ISSUE TITLE
Probar migración de archivo de usuarios

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#72]
Probar si al sobrescribir el archivo de usuarios con el que se tiene actualmente en producción se mantienen los permisos concedidos sobre los recursos

**Comment by alegnaaived** [comment]
Se mantienen los permisos sobre los recursos que asignaron permisos por interfaz del usuario y no por interfaz del recurso.

Resultado: Sí se puede usar el archivo users.xml para reemplazarlo en la nueva versión del IPT. No transfiere todos los permisos que están en el IPT Ceiba actualmente.
