### ISSUE TITLE
Revisar y ajustar la lógica para que los recursos se muestren en el perfil del usuario para ser asignados en lote

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#73]
Evaluar el comportamiento de la caja de recursos que aparece en el perfil de usuario para asignación de recursos en lote, y corregir el mismo de manera que quede funcional.

**Comment by alegnaaived** [comment]
Los recursos se muestran pero quedamos con Ángela Checa de revisar por qué no se muestran recursos para los correos @humboldt.org.co, así que vamos a validar estas funcionalidades.
