### ISSUE TITLE
Revisar configuración de notificaciones y correos en dataverse

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#74]
Revisar y entender la configuración de notificaciones y correos en la plataforma.

Definir en conjunto con Diego la política de los mismos con respecto a los roles que se van a manejar. Documentar esta política en la sección correspondiente del [documento](https://docs.google.com/document/d/1IgUlO4CXIqrNhMYzgW2r_RJ3Jl6l_p_Ta7qmeECkdRI/edit#heading=h.9ujqdspv6oga)

**Comment by Trjegul84** [comment]
Se cierra esta tarea porque la configuración de correos no es necesaria, se realizaron pruebas y esta funcionando correctamente. Los correos llegan al correo del administrador de la plataforma. Si se desea configurar las políticas de correos esto se puede realizar desde la interfaz de Dataverse y debe realizarse cuando salga a producción.
