### ISSUE TITLE
Configurar cuenta de pruebas de datacite

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#75]
Diego obtuvo una cuenta de pruebas de datacite para usar en la plataforma.

Realizar las configuraciones necesarias para que la conexión de la plataforma con datacite funcione (en modo prueba).

**Comment by Trjegul84** [comment]
Se configuró la cuenta de DataCita en dataverse mediante las jvm-options y el DOI provider mediante los comandos del API.  Sin embargo, solo con esta acción siguió mostrandose el error de que no que se puede publicar el dataset debido a la falta de un DOI autentico.

![Screenshot_20210726_021705.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/5b0a30d1-49f1-485d-b097-50e158f7bd6b)

![Screenshot_20210726_021806.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/206a0f04-086d-488d-803e-fae701de6457)

Se investigo más y se encontró que se puede hacer cortocircuito al registro de los DOIs enviando la opciones FAKE del DoiProvider mediante el api. De esta forma se logra publicar uno de los datasets de prueba.

![Screenshot_20210726_133000.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/9db06ef0-8be0-459d-b65e-b1808f0ea97c)

Ahora la función publicar si culmina con éxito pero de esta forma los enlaces DOI de cada dataset publicado NO son válidos y llevan a una página 404 dentro del dominio de Datacite.
