### ISSUE TITLE
Revisar funcionalidades desbloqueadas con la cuenta de pruebas de datacite

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#76]
Revisar si con la cuenta de pruebas de datacite ya se pueden publicar los datasets, y si ya se puede trabajar en todas las demás actividades que estaban bloqueadas por esto, por ejemplo la [exportación e importación de los datasets](https://github.com/PEM-Humboldt/dev-scrum/issues/66).

IMPORTANTE:
Cambiar el tipo de instancia AWS de la máquina de Dataverse de large a medium.

**Comment by Trjegul84** [comment]
Se comprueba que con la configuración realizada para evitar validación de DOIs se puede publicar Datasets y exportar los metadatos en formatos DDI  y Dublin Core.

Se configura solo el idioma Español en la plataforma y se cambia el tipo de instancia EC2 de _large_ a _medium_. Después de este cambio se observa el espacio de memoria de la siguiente forma:
![Screenshot_20210728_085748.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/a7279a54-7949-4826-9a31-fa12be2c2b51)
