### ISSUE TITLE
Realizar pruebas para importar metadatos DDI y Dublin Core

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#77]
- [x] Averiguar cuál es la mejor estrategia para importar metadatos.
- [ ] Documentar como es manejo y almacenamiento de archivos de datos y metadatos. 
- [ ] Realizar un prueba de importación en lote.

**Comment by Trjegul84** [comment]
NOTA:
Comando para importar datos
`curl -H X-Dataverse-key:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -X POST https://demo.dataverse.org/api/dataverses/root/datasets/:importddi?pid=doi:ZZ7/MOSEISLEYDB94&release=yes --upload-file ddi_dataset.xml`

**Comment by cazapatamar** [comment]
El comando que está en la documentación no funcionó, no reconoce el json que se está subiendo.

Se indaga y se encuentra otra estructura de la peticion al API para importar:

`curl -H X-Dataverse-key:15a2c91a-172f-4f3a-b4f7-ded8e84e2b22 -X POST -H "Content-type:application/json" -d @test.json http://23.23.47.203:8080/api/dataverses/root/datasets/:import?pid=doi:10.33518/FK2/VHT9X3&release=no`

En este caso si se reconoce el archivo que se está subiendo pero parece que se está haciendo la validación del DOI. Por lo cual en este caso no se pudo importar ningún dataset teniendo en cuenta que actualmente no tenemos configurado los DOI's reales.

Se busca si hay forma de no hacer esta validación al importar pero no se encuentra nada útil.

**Comment by Trjegul84** [comment]
Se observa que existe un bug reportado para esta funcionalidad en el repositorio de Dataverse. No funciona la importación de datasets mediante el API con los DOIs de prueba en ambiente de desarrollo.

[Import APIs don't work with DataCite test DOIs #8028 ](https://github.com/IQSS/dataverse/issues/8028)
