### ISSUE TITLE
Generar documento de recomendaciones para repositorios que no son de desarrollo

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/dev-scrum#8]

**Comment by erikasv** [comment]
@alegnaaived @cazapatamar @danflop Con la creación del template basta cierto? O igualmente deberíamos generar un documento?

**Comment by cazapatamar** [comment]
Yo creo que con el template es suficiente. Aunque eso lo podríamos hablar con Bibiana y Juan cuando nos reunamos ya que ellos les puede parecer conveniente un documento corto explicando la plantilla y el procedimiento para crear un nuevo repo, agregar un miembro a un equipo, etc.

**Comment by danflop** [comment]
Estoy de acuerdo, con el template es suficiente por ahora. A futuro se podría hacer referencia a este si se elabora un documento o wiki general de buenas prácticas en GitHub.
