### ISSUE TITLE
Investigar cómo cortocircuitar la validación de DOIs para ficheros de Dataset

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#81]
Revisar por qué a pesar de haber cortocircuitó la validación de los DOIs para poder publicar Datasets, se sigue presentando un error o mensaje de validación de DOIs cuando se modifica alguno de sus ficheros (archivos) asociados. 

![imagen_error_dataverse.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/08281d10-64be-4fc8-bbbe-00a69ca5fbeb)

**Comment by Trjegul84** [comment]
Se efectuó la configuración de _FilePIDsEnabled_ en false para evitar la validación de DOIs en ficheros.
Se procede a realizar las pruebas con el dataset que generó error por la ausencia de esa configuración y no se puede continuar con el mismo dataset (Extracción de Datos Documentales...) porque ahora todas las modificaciones a éste (metadatos, ficheros, etc) se observan bloqueadas.
 
Se realizan pruebas con otro dataset existente "Caracterización del conflicto ... "  modificando ficheros de la siguiente forma:
1. Adición de un nuevo fichero
2. Modificación del nombre de un fichero existente con otro archivo y adición de metadatos 
3. Reemplazo de fichero existente con el mismo archivo pero con datos modificados y adición de descripción en sus metadatos.

Todas las pruebas realizadas resultan exitosas. Como resultado el dataset cuenta se pública efectivamente con las respectivas versiones por cada uno de los cambios.
