### ISSUE TITLE
Revisar configuraciones de modo TEST

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#85]
1. Revisar cómo debe ser la conexión con I2D http://datos.humboldt.org.co/
1. Revisar que paso es necesario para eliminar la conexión con GBIF (especialmente porque el entorno actual es TEST y no se configuró dominio para poder tener conexiones externas)

**Comment by erikasv** [comment]
Esta tarea se realizó en alguna otra.
