### ISSUE TITLE
Spike: Cómo implementar un servicio para exponer capas geográficas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#86]
Buscar herramientas que permitan hacer esto y no requieran una aplicación completa como GeoServer, que sea de fácil integración y/o extensibles con implementaciones propias (por ejemplo servicios de JavaScript)

**Comment by alegnaaived** [comment]
https://koopjs.github.io/docs/basics/what-is-koop

**Comment by alegnaaived** [comment]
Encontré esta [presentación](http://tooshel.github.io/agic2014/#/18) que además de ser chistosa, me llevó a este recurso para usar NodeJS con PostGIS https://blog.geomusings.com/2014/02/18/a-little-deeper-with-node-and-postgis/

**Comment by alegnaaived** [comment]
Comencé a probar una [imagen de TinyOWS](https://github.com/camptocamp/docker-tinyows) y he obtenido este error "Waiting for the file /etc/mapserver/tinyows.xml to be available...", que aún no logro solucionar
![image](https://user-images.githubusercontent.com/15584917/130108383-1ffaeeba-19f3-4ec2-8ce9-0e4da18c1d91.png)

**Comment by alegnaaived** [comment]
Guía de ESRI sobre GeoServices http://geoservices.github.io/ 
y la [página](https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Education_WebMercator/MapServer/5/query?where=FACUSE%20like%20%27%Elementary%%27%20AND%20TOTAL_STUD%20%3E=%20200%20AND%20TOTAL_STUD%20%3C=%201000%20&geometry={%22xmin%22:-77.0036,%22ymin%22:38.8879,%22xmax%22:-76.98434,%22ymax%22:38.90007,%22spatialReference%22:{%22wkid%22:4326}}%20&geometryType=esriGeometryEnvelope%20&inSR=4326%20&outFields=*) con la tabla que les mostré en el daily

**Comment by alegnaaived** [comment]
De la revisión de [MapBox](https://www.mapbox.com/pricing/), si se identifica que es pago según la cantidad de usuarios y sesiones consumiendo servicios. Es muy diverso, pero sí se relaciona diferentes cantidades de pago.

**Comment by danflop** [comment]
Se verificará la funcionalidad de leer rasters desde almacenamiento con Koop para definir si se continúa con esta solución. También se probará el despliegue de MapServer como alternativa.
