### ISSUE TITLE
Creación y restauración de los backups de Dataverse

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#87]
- Plantear una estrategia para la generación de los backups de la plataforma, tener en cuenta tanto la base de datos, metadatos y ficheros.

- También se debe verificar que funcione la restauración de los mismos (ya sea en una nueva instancia o en la misma).

- Un escenario posible de restauración de backups es una migración que afecte algunas de las configuraciones que se hacen al momento de la instalación, como por ejemplo el dominio.

**Comment by erikasv** [comment]
@alegnaaived @cazapatamar @danflop @Trjegul84 Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/dev-scrum/87?planning-poker)

**Comment by Trjegul84** [comment]
Se avanzó en la configuración de una instalación de dataverse a nivel local con contenedores docker. Actualmente se esta trabajando en la configuración del ambiente local. 
* Falta realizar la prueba de restablecimiento de la base de datos.

**Comment by Trjegul84** [comment]
Basándose en los docker compose de [IQSS](https://github.com/IQSS/dataverse-docker/blob/master/docker-compose-local.yml) se creo un ambiente local con contenedores docker para desplegar Dataverse y hasta el momento se logró que funcione correctamente con la versión 5.2 de Dataverse. Sin embargo, con la versión 5.5 el docker-compose creado presenta problemas. El repositorio de IQSS dataverse-docker no esta actualizado y no cuenta con la actualización de las ultimas versiones.

**Pruebas de restauración de backup**
Se obtuvo un dump de la BD y se copió la carpeta files de glassfish de la instalación de Dataverse que tenemos en AWS.

**- Prueba fallida No.1**
Se intentó restablecer la BD en el ambiente local con docker usando las opciones de `pg_restore --data-only --disable-triggers`. 
Con esto la aplicación funciona correctamente pero no se observan los datos aún cuando se ejecuta los comandos de re- indexación de Solr. Esto es debido a que no se copian todos los datos de la BD original. Se presentan problemas porque al realizar _pg_restore_ se mostraron errores y no se pasaron todos los datos en todas las tablas, algunas continúan con los datos de la instalación local y por eso no se observan los dataverses. 

**- Prueba fallida No.2**
Restablecimiento de la BD completa.
Se borraron todos los datos de la BD del contenedor postgres local y se restablecieron siguiendo el mismo procedimiento usado para restablecer la BD de Biotablero y con esta opción la aplicación no funciona y presenta el error 404 cuando se ingresa al index.

![Screenshot_20210916_170541.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/2bfa64b1-7037-40d5-b4e8-3ced59369afa)

Se analiza las diferencias entre las dos bases de datos AWS vs Docker local y se encuentra que debido las diferencias de versiones (5.5 vs 5.2) existen 4  tablas de más en la versión 5.2 (local) comparado con la BD en AWS.
Número de tablas versión local = 109 - Número de tablas versión AWS = 105
Esas tablas son: `maplayermetadata,  worldmapauth_token,  worldmapauth_tokentype  y  EJB__TIMER__TBL`     

**CONCLUSIONES**
- Se concluye que por las diferencias de versiones de las BD probablemente éstas no son compatibles, por lo tanto no se puede hacer la migración borrando la BD y restaurándola en su totalidad.
- Se debe modificar el docker-compose para desplegar localmente una versión de Dataverse compatible con la versión en AWS.
- Es necesario revisar el proceso de actualización de versión de una instalación de Dataverse.

**Comment by cazapatamar** [comment]
Primero llevar el docker-compose a la 5.5 y luego continuar con la migración

**Comment by Trjegul84** [comment]
Se concluye que se debe hacer más esfuerzos para completar una versión estable de la instalación con Docker por esa razón se deja esa tarea en stand-by y se continúa con la restauración de backups en otra maquina AWS igual a la que ya se tiene en pruebas de Dataverse. 

Se procedió a instalar dataverse 5.5 en otra máquina de AWS (`.149`) y todos los programas necesarios con las mismas versiones de la máquina `.203 `
Para la prueba del backup se usa el dump realizado a la máquina AWS .203 el dia 16 de septiembre y se reestablece el dump en la nueva máquina 149 logrando que funcione.
Se configura de nuevo los fake DOIs y se copian los archivos de la otra máquina de AWS.
**NOTA:**
Es importante tener en cuenta que el dump debe sacarse completo y el server de destino debe borrarse la base de datos que genera en la instalación y volver a crear la bd limpia para poder restablecer con pg_restore. Además el usuario en el server destino debe tener el mismo nombre de base de datos, mismo usuario y la misma contraseña que se configura en la instalación de dataverse del 203.

Después de restablecer la base de datos lo más importante para que funcione la restauración es ejecutar los comandos de [re-indexación de Solr ](https://guides.dataverse.org/en/latest/admin/solr-search-index.html?highlight=solr#clear-and-reindex) porque sin esto no funciona la migración.
 
![Screenshot_20211004_190231.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/4c5d5952-49a8-47d7-b236-7e8380497ed4)
