### ISSUE TITLE
Ajuste de traducciones de Dataverse

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#88]
- Verificar la lista de errores de traducción con la ubicación del lugar a aplicar en la interfaz
- Revisar si hay nuevas actualizaciones para español en el repositorio de IQSS https://github.com/IQSS/dataverse 
- Si es posible realizar un PR sobre rama de lenguaje del repositorio IQSS

**Comment by Trjegul84** [comment]
Se consulta el repositorio de [idiomas de Dataverse ](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs) y se observa que no hay actualizaciones recientes, este repositorio continua con las mismas traducciones desde hace dos años. 
Se compara los archivos `properties` de las traducciones de Español e inglés y se observa que `es_ES/Bundle_es.properties` tiene propiedades muy diferentes y desactualizadas respecto a las de la versión de inglés; por lo que existirán problemas en diferentes mensajes dentro de la interfaz en Español. La versión de las traducciones en español es para la versión dataverse 4.19 y tenemos instalada la versión 5.5 además la versión de las traducciones ya esta actualizada en la versión de Dataverse 5.8.
Por ejemplo en el archivo [en_US/Bundle.properties](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/develop/en_US/Bundle.properties) dataset.accessBtn.too.big es una propiedad que si esta definida y tiene cadena asociada pero en la versión en inglés no. 

**Conclusión:**
Para actualizar el idioma se debe ingresar a la lista de correo de traducciones de dataverse para conocer los lineamientos de la comunidad y unirse al grupo de traductores de Dataverse. 
Luego se debe comparar los archivos Bundle.properties de inglés y español y completar todas las traducciones que faltan y actualizar las propiedades obsoletas (este proceso parece un poco demorado).
Con estos cambios crear un PR en el repositorio de `dataverse-language-packs`.

**Comment by Trjegul84** [comment]
@danflop por favor revisar los comentarios de esta tarea para llegar a un acuerdo sobre la estrategia a seguir respecto, ya que si se sigue usando la herramienta en Español es muy probable que al pasar a producción se muestren varios mensajes o elementos de la interfaz sin traducción.

**Comment by erikasv** [comment]
Se ha decidido posponer los ajustes mencionados en esta tarea hasta definir un plano de ruta más general con Diego.
