### ISSUE TITLE
Revisar falla en la migración de recursos con archivos dwca

### ISSUE THREAD

**Issue by Trjegul84** [PEM-Humboldt/dev-scrum#89]
La migración de recursos de Ceiba (producción) a Ceiba v2.5 (migración) no esta funcionando cuando las carpetas de los recursos tienen datos de espécimen en formato Darwin Core, es decir archivos **dwca.zip.** 
Nota: 
Cuando los recursos no tienen ese tipo de archivos la migración si funciona ver tarea **dev-scrum** #71

**Comment by alegnaaived** [comment]
Se comprobó el listado de los recursos mostrados por la lista del IPT. 
![image](https://user-images.githubusercontent.com/15584917/128802612-4f942a37-f867-49d4-9bea-57c0cf838664.png)

Se identificó la función que carga los recursos desde el directorio:
![image](https://user-images.githubusercontent.com/15584917/128803082-790151cb-8a74-47a0-b14c-c21029ec26d5.png)

Y en la línea que se implementa:

**Comment by alegnaaived** [comment]
Creé una cuenta en gbif para usar el validador y el error que aparece es de licencia del recurso:
![image](https://user-images.githubusercontent.com/15584917/128805979-3831cbf4-07f8-4bb0-8578-40f14852b5d3.png)
![image](https://user-images.githubusercontent.com/15584917/128806252-c8027a8f-9958-4181-bf0d-b0fb5c8d7b44.png)

**Comment by Trjegul84** [comment]
Se revisan las carpetas del servidor y se encuentran dos carpetas relacionadas con las extensiones y que causan el problema de carga de ciertos recursos con archivos dwca.zip.

```
/config/.extensions
/config/.vocabularies
```

Una vez se copian todos los archivos de esas carpetas al ambiente de desarrollo con Ceiba ipt v2.5 todos los recursos copiados cargan, aunque se sigue presentando el warning relacionado con la actualización de la fecha de modificación de los metadatos, la migración de todos los recursos esta funcionando.

**Comment by Trjegul84** [comment]
Pasos a seguir:
- Pruebas de crear y borrar un recurso para analizar las carpetas o archivos que quedan en el servidor
- Pruebas de la instalación directa de extensiones desde la plataforma para verificar si se generan errores en los recursos.
- Compañera de I2D se encargará de realizar un inventario con las cantidades de recursos públicos, privados y en proceso para tener como referencia al realizar la migración.

**Comment by alegnaaived** [comment]
Sobre los pasos descritos:
 - Se probó eliminando recursos (en las dos opciones que salen en la imagen) y efectivamente se elimina la carpeta del directorio del IPT.
 
 Imagen de nuestro branch ceiba_master:
 ![image](https://user-images.githubusercontent.com/15584917/129084276-26c4de80-2601-49fd-894b-ef032645683a.png)
 Imagen de la versión actualizada con master de GBIF:
 ![image](https://user-images.githubusercontent.com/15584917/129083399-85ec21c7-eb18-44ba-ba36-c68b9661e5b4.png)

 - En la versión que tenemos en el branch ceiba_master salieron errores al instalar extensiones y no identificaba vocabularios. Se probó con la última versión de master en el [repositorio de GBIF](https://github.com/gbif/ipt) y este error ya no se presenta. Dado esto, necesitamos actualizar el branch ceiba_master con el branch master.
 - La tarea del inventario de recursos públicos, privados y en proceso de publicación sigue en proceso a cargo de Carolina Castro. También nos indicó que hablemos con ella cuando queramos validar si la cantidad de recursos con cada acceso es la correcta.
