### ISSUE TITLE
Crear dockerfile para IPT

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/dev-scrum#92]
Dado que el proyecto que estamos editando no coincidirá con el proyecto que quede colgado en [Docker Hub](https://hub.docker.com/r/gbif/ipt), necesitamos crear una imagen de docker para IPT Ceiba 2.5.

[Aquí está el último dockerfile de GBIF](https://github.com/gbif/docker-ipt/blob/master/Dockerfile).

**Comment by alegnaaived** [comment]
Se creó el Dockerfile y se mapeó el puerto (-p 8083:8080). Se está obteniendo este error al ejecutar el IPT en modo test, porque pide URL pública a pesar de ser un IPT en modo prueba:
![image](https://user-images.githubusercontent.com/15584917/132442915-b5697d0a-8f52-441d-ad31-bbd56e99d667.png)

**Comment by alegnaaived** [comment]
El siguiente dockerfile fue validado en el computador de @Trjegul84 y @alegnaaived:

FROM tomcat:8.5-jdk8
LABEL MAINTAINERS="adevia@humboldt.org.co, acheca@humboldt.org.co"

ARG IPT_VERSION=2.5.0
ARG IPT_NAME=ROOT

# path y nombre del archivo donde se ubica el .war de forma local 

ENV WAR_LOCAL_DIR=ipt/target/ipt-2.5.0-SNAPSHOT-re590618.war
ENV IPT_DATA_DIR=/srv/datadir
 
RUN rm -Rf /usr/local/tomcat/webapps \
    && mkdir -p /usr/local/tomcat/webapps/${IPT_NAME} \
    && mkdir -p ${IPT_DATA_DIR} 

COPY ${WAR_LOCAL_DIR} /usr/local/tomcat/webapps/${IPT_NAME}

WORKDIR /usr/local/tomcat/webapps/${IPT_NAME} 
RUN mv ipt-2.5.0-SNAPSHOT-re590618.war ipt.war \
    && unzip -d /usr/local/tomcat/webapps/${IPT_NAME} ipt.war \
    && rm -f ipt.war

VOLUME /srv/ipt

EXPOSE 8080
CMD ["catalina.sh", "run"]

**Comment by Trjegul84** [comment]
El docker file anterior presenta errores. Se debe configurar /srv/ipt dentro del contenedor a las variables de entono del dockerfile. El docker file final que funciona es:
FROM tomcat:8.5-jdk8
LABEL MAINTAINERS="adevia@humboldt.org.co, acheca@humboldt.org.co"

ARG IPT_VERSION=2.5.0
ARG IPT_NAME=ROOT

# path y nombre del archivo donde se ubica el .war de forma local 

ENV WAR_LOCAL_DIR=ipt_ceiba/ipt-2.5.0-SNAPSHOT-re590618.war
ENV IPT_DATA_DIR=/srv/ipt  
 
RUN rm -Rf /usr/local/tomcat/webapps \
    && mkdir -p /usr/local/tomcat/webapps/${IPT_NAME} \
    && mkdir -p ${IPT_DATA_DIR} 

COPY ${WAR_LOCAL_DIR} /usr/local/tomcat/webapps/${IPT_NAME}

WORKDIR /usr/local/tomcat/webapps/${IPT_NAME} 
RUN mv ipt-2.5.0-SNAPSHOT-re590618.war ipt.war \
    && unzip -d /usr/local/tomcat/webapps/${IPT_NAME} ipt.war \
    && rm -f ipt.war

VOLUME /srv/ipt

EXPOSE 8080
CMD ["catalina.sh", "run"]

**Comment by Trjegul84** [comment]
Para crear la imagen:
docker run --detach  --name ceibadocker --volume /path/directorio/data/en/host:/srv/ipt --publish 8080:8080 ceiba/2.5.0

**Comment by Trjegul84** [comment]
Para que funcione la migración de los usuarios, antes de modificar users.xml es necesario detener el contenedor.
