### ISSUE TITLE
Spike: Docker para dataverse

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/dev-scrum#93]
Ampliar descripción en su momento pero tener en cuenta abordar esta tarea desde estos 3 puntos de vista:

- [Docker experimental oficial](https://github.com/IQSS/dataverse-docker)
- [Kubernetes experimental oficial](https://github.com/IQSS/dataverse-kubernetes)
- Construir docker manualmente

**Comment by Trjegul84** [comment]
Se creo un archivo docker-compose a partir de los archivos yml del repositorio [dataverse-docker de IQSS](https://github.com/IQSS/dataverse-docker)
La aplicación funciona correctamente de manera local con los siguientes contenedores:  `dataverse-docker_reverse-proxy_1 dbgui solr repo whoami dataverse  postgres`). Sin embargo, se debe tener en cuenta lo siguiente:
- La imagen de postgres que debe ser usada es ` library/postgres:13.3` para que funcione el comando `pg_restore` cuando se restablece localmente el dump de la instalación en AWS.
- También es necesario quitar las configuraciones de _certificatesresolvers_  y los labels de traefik cuando se quiere desplegar de forma local. Además es necesario eliminar la configuración del puerto 443.
- El archivo .env debe tener la misma configuración de las credenciales de postgres que la instalación en AWS para que funcione el comando pg_restore en el contenedor local.
 
Todas las configuraciones realizadas se orientaron a un despliegue local (sin nombre de dominio), donde no interviene el DNS, en un despliegue en producción es probable que el archivo docker-compose creado presente fallas.
