### ISSUE TITLE
Listar backups pendientes

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/dev-scrum#95]
Crear una tarea con los backups pendientes por crear, arreglar, poner a funcionar, etc.

Documentar la política de cada caso en el [inventario](https://docs.google.com/spreadsheets/d/1zzfVGjSrWLbGRnFBhXwuUQ9MPAajTuRcHqKtaUygCzM/edit#gid=1326233070)

**Comment by erikasv** [comment]
En esta [tarea](https://github.com/PEM-Humboldt/dev-scrum/issues/65) se están listando las actividades pendientes relacionadas con los backups en los servidores, faltarían el 60, el 70 y el 58

**Comment by alegnaaived** [comment]
Se agregaron los servidores 105, 60, 70 y 58, y se agregó también la descripción de tareas adicionales sobre credenciales de aplicaciones que aún no está en el [inventario](https://docs.google.com/spreadsheets/d/1zzfVGjSrWLbGRnFBhXwuUQ9MPAajTuRcHqKtaUygCzM/edit#gid=1326233070)
